"use client";
import {useState,useEffect,useCallback,type FormEvent} from 'react';
import {usePathname,useRouter} from 'next/navigation';
import {Home,Compass,Bookmark,Users,Upload,KeyRound,Settings,LogOut,Search,Play,Headphones,Image as ImageIcon,FileText,ArrowRight,LockKeyhole,Check,Plus,Menu,Trash2,ExternalLink,Wallet,LoaderCircle,Sparkles,MessageCircle,RefreshCw,ArrowDownWideNarrow,Pencil} from 'lucide-react';
import type {Address} from 'viem';
import {Brand,CreatorAvatar,ContentCard,ContentMedia} from '@/components/keytube-content';
import {Modal,AuthForm,PlanEditor,Publisher} from '@/components/keytube-forms';
import {api,connectWallet,signProof,checkoutUrl,errorText,shortAddress,mediaLabels} from '@/lib/keytube-client';
import {CATEGORIES,type PublicPost,type FullContent,type CreatorPlan,type ContentType,type Membership} from '@/lib/keytube-types';
import {FeedPost} from '@/components/keytube-feed';
import {ProfileEditor} from '@/components/keytube-profile';
import {PostSettings} from '@/components/keytube-post-settings';
import {WalletConnector} from '@/components/keytube-wallet';
import {disconnectWallet,getWalletState,openWalletConnection,subscribeWallet,WalletError} from '@/lib/wallet-connection';
import {useKeyTubeFeed} from '@/lib/use-keytube-feed';
import './keytube-v2.css';
type User={id:string;name:string;email?:string};
type Account={profile:{name:string;bio:string;avatar:string}|null;saved:string[];following:string[];postCount:number};
type Comment={id:string;name:string;body:string;created_at:number};
const emptyAccount:Account={profile:null,saved:[],following:[],postCount:0};
const filters=[{name:'Todos',icon:Compass},{name:'Videos',icon:Play},{name:'Imágenes',icon:ImageIcon},{name:'Audio',icon:Headphones},{name:'Documentos',icon:FileText}];
const typeFilter:Record<string,string>={Videos:'video',Imágenes:'image',Audio:'audio',Documentos:'document'};
export default function KeyTubeV2({user:initialUser}:{user:User|null;signInUrl?:string}) {
  const router=useRouter(),path=usePathname();
  const [user,setUser]=useState(initialUser),[account,setAccount]=useState<Account>(emptyAccount),[myPlans,setMyPlans]=useState<CreatorPlan[]>([]),[error,setError]=useState(''),[toast,setToast]=useState(''),[auth,setAuth]=useState(false),[google,setGoogle]=useState(false),[mobile,setMobile]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('Todos'),[freeOnly,setFreeOnly]=useState(false),[wallet,setWallet]=useState<Address|null>(null);
  const [post,setPost]=useState<PublicPost|null>(null),[full,setFull]=useState<FullContent|null>(null),[creatorPlans,setCreatorPlans]=useState<CreatorPlan[]>([]),[purchase,setPurchase]=useState(false),[verifying,setVerifying]=useState(false),[comments,setComments]=useState<Comment[]>([]),[comment,setComment]=useState(''),[commentBusy,setCommentBusy]=useState(false),[legacyQuote,setLegacyQuote]=useState<Membership|null>(null),[deletePost,setDeletePost]=useState<PublicPost|null>(null),[deleting,setDeleting]=useState(false),[deleteError,setDeleteError]=useState('');
  const studio=path.startsWith('/studio'),upload=path==='/studio/upload',planView=path==='/memberships',profileView=path==='/profile',savedView=path==='/saved',followingView=path==='/following',contentId=path.startsWith('/content/')?decodeURIComponent(path.split('/')[2]):null,creatorId=path.startsWith('/creator/')?decodeURIComponent(path.split('/')[2]):null;
  useEffect(()=>setDeleteError(''),[deletePost?.id]);
  const [managePost,setManagePost]=useState<PublicPost|null>(null);
  const [order,setOrder]=useState<'desc'|'asc'>('desc'),[creatorProfile,setCreatorProfile]=useState<{name:string;bio:string;avatar:string;postCount:number}|null>(null);
  const feedQuery=new URLSearchParams({view:studio?'mine':savedView?'saved':followingView?'following':'all',order,q:search,free:freeOnly?'1':'0',type:typeFilter[filter]||'',category:filter!=='Todos'&&!typeFilter[filter]?filter:'',creator:creatorId||''}).toString();
  const {posts,loading,loadingMore,hasMore,refresh:refreshPosts,loadMore,error:feedError}=useKeyTubeFeed(feedQuery,!(studio||savedView||followingView)||!!user);
  const navigate=(url:string)=>{setMobile(false);setError('');router.push(url);};
  const refreshAccount=useCallback(async()=>{const [s,a]=await Promise.all([api<{user:User|null;googleEnabled:boolean}>('/api/auth/session'),api<Account>('/api/account')]);setUser(s.user);setGoogle(s.googleEnabled);setAccount(a);return s.user;},[]);
  const refreshPlans=useCallback(async()=>{const r=await api<{plans:CreatorPlan[]}>('/api/plans');setMyPlans(r.plans);},[]);
  useEffect(()=>{refreshAccount().catch(e=>setError(errorText(e)));const params=new URLSearchParams(window.location.search);if(params.has('authError')){setAuth(true);const code=params.get('authError');setError(code==='use_password'?'Ese correo ya tiene una cuenta. Inicia sesión con tu contraseña.':code==='google_unavailable'?'Google todavía no está configurado en este proyecto.':'No se completó el acceso con Google. Puedes volver a intentarlo.');}if(params.has('login'))setAuth(true);},[refreshAccount]);
  useEffect(()=>{if(user)refreshPlans().catch(e=>setError(errorText(e)));else setMyPlans([]);},[user?.id,refreshPlans]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t);},[toast]);
  useEffect(()=>{let revision=getWalletState().revision;return subscribeWallet(()=>{const current=getWalletState();setWallet(current.address);if(current.revision!==revision){setFull(null);revision=current.revision;}});},[]);
  useEffect(()=>{if(!full?.expiresAt)return;const t=setTimeout(()=>{setFull(null);setToast('Vuelve a verificar tu membresía para continuar.');},Math.max(0,full.expiresAt-Date.now()));return()=>clearTimeout(t);},[full]);
  useEffect(()=>{
    let active=true;setFull(null);setPurchase(false);setPost(null);setComments([]);setCreatorPlans([]);setLegacyQuote(null);
    if(!contentId)return;
    const get=api<{post:PublicPost}>(`/api/posts?id=${encodeURIComponent(contentId)}`);
    get.then(async r=>{if(!active)return;setPost(r.post);
      const jobs:Promise<void>[]=[];
      if(r.post.creator_id===user?.id||r.post.visibility==='free')jobs.push(api<FullContent>((r.post.creator_id===user?.id?'/api/studio?post=':'/api/free-content?post=')+r.post.id).then(d=>{if(active)setFull(d);}));
      jobs.push(api<{plans:CreatorPlan[]}>(`/api/plans?creator=${encodeURIComponent(r.post.creator_id||'')}`).then(d=>{if(active)setCreatorPlans(d.plans);}));
      if(r.post.lock&&!r.post.plan_id)jobs.push(api<Membership>(`/api/membership?post=${r.post.id}`).then(d=>{if(active)setLegacyQuote(d);}));
      if(r.post.status!=='hidden')jobs.push(api<{comments:Comment[]}>(`/api/comments?post=${r.post.id}`).then(d=>{if(active)setComments(d.comments);}));
      await Promise.all(jobs);
    }).catch(e=>{if(active)setError(errorText(e));});return()=>{active=false;};
  },[contentId]);
  useEffect(()=>{setCreatorProfile(null);if(!creatorId)return;let active=true;Promise.all([api<{plans:CreatorPlan[]}>(`/api/plans?creator=${encodeURIComponent(creatorId)}`),api<{profile:{name:string;bio:string;avatar:string};postCount:number}>(`/api/account?creator=${encodeURIComponent(creatorId)}`)]).then(([plans,data])=>{if(active){setCreatorPlans(plans.plans);setCreatorProfile({...data.profile,postCount:data.postCount});}}).catch(e=>{if(active)setError(errorText(e));});return()=>{active=false;};},[creatorId]);
  function needUser(){if(user)return true;setAuth(true);return false;}
  async function social(kind:'save'|'follow',target:string){if(!needUser())return;try{const list=kind==='save'?account.saved:account.following,active=!list.includes(target);await api('/api/social',{kind,target,active});await refreshAccount();if((savedView&&kind==='save')||(followingView&&kind==='follow'))await refreshPosts();setToast(kind==='save'?(active?'Publicación guardada':'Publicación eliminada de guardados'):(active?'Ahora sigues a este creador':'Dejaste de seguir a este creador'));}catch(e){setError(errorText(e));}}
  async function verify(){if(!post)return;setVerifying(true);setError('');try{const address=await connectWallet();setWallet(address);const proof=await signProof('read',address,post.network,{postId:post.id});const data=await api<FullContent>('/api/access',{postId:post.id,...proof});setFull(data);setPurchase(false);setToast('Membresía válida. Ya puedes disfrutar el contenido completo.');}catch(e){setError(errorText(e));setPurchase(true);}finally{setVerifying(false);}}
  async function buy(plan?:CreatorPlan){if(!post||!needUser())return;try{const address=await connectWallet();setWallet(address);window.location.assign(checkoutUrl(plan?{...post,lock:plan.lock,network:plan.network}:post,address));}catch(e){setError(errorText(e));}}
  async function addComment(e:FormEvent){e.preventDefault();if(!post||!needUser())return;setCommentBusy(true);try{const r=await api<{comment:Comment}>('/api/comments',{postId:post.id,body:comment});setComments(c=>[r.comment,...c]);setComment('');}catch(e){setError(errorText(e));}finally{setCommentBusy(false);}}
  async function logout(){try{await api('/api/auth/logout',{});setUser(null);setAccount(emptyAccount);setFull(null);disconnectWallet();setWallet(null);setMyPlans([]);navigate('/');setToast('Sesión cerrada.');}catch(e){setError(errorText(e));}}
  const creator=posts[0],filtered=posts;
  const locked=!!post&&!full&&post.visibility!=='free';
  const eligible=creatorPlans.filter(p=>post&&(p.lock.toLowerCase()===post.lock.toLowerCase()||p.lock.toLowerCase()===post.premium_lock?.toLowerCase()));
  const renderPlans=(items:CreatorPlan[],buyButtons:boolean)=> <div className="k2-plan-grid">{items.map(p=><article className={`k2-plan-card ${p.slot==='premium'?'premium':''}`} key={p.id}><span className="k2-badge"><KeyRound size={13}/>{p.slot==='basic'?'Básico':'Premium'}</span><h2>{p.name}</h2><p>{p.description}</p><div className="k2-price">{p.quote?`${p.quote.price} ${p.quote.currency}`:'Precio por confirmar'}<small>{p.quote?p.quote.duration:`${p.durationDays} días`}</small></div><ul>{p.slot==='premium'&&<li><Check size={16}/>Todo el contenido del Básico</li>}{p.benefits.map((b,i)=><li key={i}><Check size={16}/>{b}</li>)}<li><Check size={16}/>{p.coverage.map(t=>mediaLabels[t]).join(' · ')}</li></ul><small>{p.network===84532||p.network===11155111?'Red de pruebas · sin cobros reales':'El pago se realiza en la red del plan'}</small>{buyButtons&&<button className="k2-primary" onClick={()=>buy(p)}>Comprar {p.name}<ArrowRight size={16}/></button>}</article>)}</div>;
  const card=(p:PublicPost)=><div key={p.id}><ContentCard post={p} saved={account.saved.includes(p.id)} onOpen={()=>navigate('/content/'+p.id)} onSave={()=>social('save',p.id)} onCreator={()=>navigate('/creator/'+(p.creator_id||''))}/>{studio&&<button className="k2-delete" onClick={()=>setDeletePost(p)}><Trash2 size={14}/> Eliminar publicación</button>}</div>;
  return <div className="k2-app"><aside className={`k2-sidebar ${mobile?'open':''}`}><button className="k2-brand-link" onClick={()=>navigate('/')} aria-label="KeyTube inicio"><Brand/></button><nav aria-label="Principal">{[{url:'/',label:'Inicio',icon:Home},{url:'/explore',label:'Explorar',icon:Compass},{url:'/saved',label:'Guardados',icon:Bookmark},{url:'/following',label:'Siguiendo',icon:Users}].map(n=><button key={n.url} className={path===n.url?'active':''} onClick={()=>navigate(n.url)}><n.icon size={19}/>{n.label}</button>)}<span className="k2-nav-caption">TU ESTUDIO</span>{[{url:'/studio',label:'Mi contenido',icon:Play},{url:'/studio/upload',label:'Subir contenido',icon:Upload},{url:'/memberships',label:'Mis planes',icon:KeyRound},{url:'/profile',label:'Mi cuenta',icon:Settings}].map(n=><button key={n.url} className={path===n.url?'active':''} onClick={()=>{if(needUser())navigate(n.url);}}><n.icon size={19}/>{n.label}</button>)}</nav><div className="k2-sidebar-card"><Sparkles size={26}/><strong>Tu talento tiene valor.</strong><p>Comparte lo que creas. Construye tu comunidad.</p><button className="k2-primary" onClick={()=>{if(needUser())navigate('/studio/upload');}}>Empezar a crear</button></div><span className="k2-powered"><LockKeyhole size={15}/> Membresías con <strong>Unlock</strong></span></aside>
    <div className="k2-page"><header className="k2-topbar"><button className="k2-icon k2-mobile-menu" aria-label="Abrir menú" onClick={()=>setMobile(!mobile)}><Menu size={22}/></button><label className="k2-search"><Search size={19}/><input value={search} onChange={e=>setSearch(e.target.value)} maxLength={120} placeholder="Busca creadores, contenido o categorías…" aria-label="Buscar contenido"/></label><div className="k2-top-actions">{user?<><button className="k2-secondary k2-upload-button" onClick={()=>navigate('/studio/upload')}><Plus size={17}/> Crear</button><button className="k2-user" onClick={()=>navigate('/profile')}><CreatorAvatar name={account.profile?.name||user.name} avatar={account.profile?.avatar}/><span>{account.profile?.name||user.name}</span></button></>:<><button className="k2-secondary" onClick={()=>setAuth(true)}>Iniciar sesión</button><button className="k2-primary" onClick={()=>setAuth(true)}>Crear cuenta</button></>}</div></header>
    <main className="k2-main">{error&&<div className="k2-error k2-global-error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Cerrar mensaje">×</button></div>}
    {(studio||planView||profileView||savedView||followingView)&&!user?<div className="k2-empty"><KeyRound size={40}/><h1>Entra a tu cuenta para continuar</h1><p>Crea tu perfil y empieza a compartir contenido.</p><button className="k2-primary" onClick={()=>setAuth(true)}>Iniciar sesión o registrarme</button></div>:
    contentId?<>{post?<div className="k2-content-layout"><section><button className="k2-back" onClick={()=>navigate('/')}>← Volver a explorar</button><div className="k2-media-wrap"><ContentMedia post={post} full={full} onPreviewEnd={()=>setPurchase(true)} onError={()=>{setFull(null);setError('No se pudo reproducir el archivo. Si tu acceso venció, vuelve a verificar tu membresía.');}}/>{locked&&purchase&&<div className="k2-player-gate"><span className="k2-large-lock"><LockKeyhole size={30}/></span><h2>Esto es solo el comienzo.</h2><p>El adelanto terminó. Hazte miembro para disfrutar el contenido completo.</p><button className="k2-primary" onClick={()=>document.getElementById('buy-plans')?.scrollIntoView({behavior:'smooth'})}>Ver membresías<ArrowRight size={17}/></button></div>}</div>
      <div className="k2-post-heading">{user?.id===post.creator_id&&<div className="k2-post-owner-controls"><button className="k2-secondary" onClick={()=>setManagePost(post)}><Settings size={16}/>Acceso y visibilidad</button><button className="k2-delete" onClick={()=>setDeletePost(post)}><Trash2 size={16}/>Eliminar</button>{post.status==='hidden'&&<span className="k2-badge">Oculta · solo tú</span>}</div>}<span className={`k2-badge ${full?'free':''}`}>{full?<><Check size={12}/> Contenido completo</>:post.visibility==='free'?'Gratis':<><LockKeyhole size={12}/> Adelanto gratis</>}</span><h1>{post.title}</h1><div className="k2-row"><button className="k2-creator-button" onClick={()=>navigate('/creator/'+post.creator_id)}><CreatorAvatar name={post.creator} avatar={post.avatar}/><span><strong>{post.creator}</strong><small>{post.category} · {mediaLabels[post.type||'text']}</small></span></button><button className="k2-secondary" onClick={()=>social('follow',post.creator_id||'')}>{account.following.includes(post.creator_id||'')?'Siguiendo':'Seguir'}</button><button className="k2-icon" aria-label="Guardar publicación" onClick={()=>social('save',post.id)}><Bookmark fill={account.saved.includes(post.id)?'currentColor':'none'} size={19}/></button></div><p>{post.intro}</p>{full?.body&&<div className="k2-full-text">{full.body}</div>}</div>
      {locked&&<section id="buy-plans" className="k2-access-panel"><span className="k2-eyebrow">TU LLAVE AL CONTENIDO COMPLETO</span><h2>Elige cómo apoyar a {post.creator}</h2><p>Cada membresía pertenece a este creador. El acceso se comprueba con tu Key de Unlock.</p>{renderPlans(eligible,true)}{!eligible.length&&<div className="k2-notice"><p>{legacyQuote?`${legacyQuote.name} · ${legacyQuote.price} ${legacyQuote.currency} · ${legacyQuote.duration}`:'El precio y la duración se muestran al abrir Unlock.'}</p><button className="k2-primary" onClick={()=>buy()}>Comprar membresía<ExternalLink size={16}/></button></div>}<button className="k2-secondary k2-verify" disabled={verifying} onClick={verify}>{verifying?<LoaderCircle size={17} className="k2-spin"/>:<Wallet size={17}/>} {verifying?'Verificando membresía…':'Ya tengo membresía · verificar acceso'}</button><small>Después de comprar y volver a KeyTube, verifica tu acceso con la wallet que recibió la membresía.</small>{user?.id===post.creator_id&&<button className="k2-secondary" onClick={async()=>{try{setFull(await api<FullContent>('/api/studio?post='+post.id));setPurchase(false);setToast('Vista privada del creador.');}catch(e){setError(errorText(e));}}}>Ver mi archivo completo</button>}</section>}
      {post.status!=='hidden'&&<section className="k2-comments"><h2><MessageCircle size={20}/> Comentarios <span>{comments.length}</span></h2><form onSubmit={addComment}><input value={comment} onChange={e=>setComment(e.target.value)} minLength={2} maxLength={1000} required placeholder={user?'Comparte lo que te gustó…':'Inicia sesión para comentar'}/><button className="k2-primary" disabled={commentBusy}>Publicar</button></form>{comments.map(c=><article key={c.id}><CreatorAvatar name={c.name}/><div><strong>{c.name}</strong><small>{new Date(c.created_at).toLocaleDateString('es')}</small><p>{c.body}</p></div></article>)}{!comments.length&&<p>Sé la primera persona en comentar.</p>}</section>}</section><aside className="k2-related"><h3>Sigue descubriendo</h3>{posts.filter(p=>p.id!==post.id).slice(0,4).map(card)}</aside></div>:<div className="k2-empty">{error?<><h2>No se pudo abrir la publicación</h2><button className="k2-secondary" onClick={()=>navigate('/')}>Volver al muro</button></>:<><LoaderCircle className="k2-spin"/><p>Cargando publicación…</p></>}</div>}</>:
    upload?<><div className="k2-section-heading"><div><span className="k2-eyebrow">TU ESTUDIO CREATIVO</span><h1>Comparte algo extraordinario.</h1><p>Tu contenido, tus reglas. Decide qué muestras y qué desbloquean tus miembros.</p></div></div><Publisher creator={account.profile?.name||user!.name} plans={myPlans} onPublished={p=>{setToast('Tu publicación ya está disponible.');refreshPosts().catch(e=>setError(errorText(e)));refreshAccount().catch(e=>setError(errorText(e)));navigate('/content/'+p.id);}}/></>:
    planView?<><div className="k2-section-heading"><div><span className="k2-eyebrow">MONETIZA TU COMUNIDAD</span><h1>Dos planes. Tú decides el valor.</h1><p>Elige precios, beneficios y formatos. Cada plan utiliza su propio Lock de Unlock.</p></div><a className="k2-secondary" href="https://app.unlock-protocol.com/locks" target="_blank" rel="noreferrer">Mi cuenta de Unlock<ExternalLink size={16}/></a></div><div className="k2-notice"><KeyRound size={20}/><span>Conecta tu propia wallet para administrar tus membresías. Usa la misma wallet y la misma red para ambos planes. Premium incluye lo publicado en Básico.</span></div><div className="k2-plan-grid">{(['basic','premium'] as const).map(slot=><PlanEditor key={`${slot}-${myPlans.find(p=>p.slot===slot)?.id||'new'}`} slot={slot} existing={myPlans.find(p=>p.slot===slot)} sibling={myPlans.find(p=>p.slot!==slot)} onSaved={()=>{refreshPlans().catch(e=>setError(errorText(e)));setToast('Plan conectado con Unlock.');}}/>)}</div></>:
    profileView?<><div className="k2-section-heading"><div><span className="k2-eyebrow">TU ESPACIO EN KEYTUBE</span><h1>Mi perfil y mi cuenta</h1><p>Tu foto, tu historia y todo lo que compartes.</p></div></div><ProfileEditor user={user!} profile={account.profile} postCount={account.postCount} planCount={myPlans.length} followingCount={account.following.length} google={google} walletLabel={wallet?shortAddress(wallet):'Conectar mi wallet'} onNavigate={navigate} onLogout={logout} onWallet={async()=>{try{setWallet(await openWalletConnection());setToast('Wallet conectada. Ya puedes verificar tus membresías.');}catch(e){if(!(e instanceof WalletError&&e.code==='WALLET_CANCELLED'))setError(errorText(e));}}} onSaved={async()=>{await refreshAccount();await refreshPosts();setToast('Perfil actualizado. Tus publicaciones muestran el nuevo nombre y foto.');}}/></>:
    <div className="k2-feed-layout"><section className="k2-feed">
      {creatorId&&<div className="k2-creator-hero"><CreatorAvatar name={creatorProfile?.name||creator?.creator||'Creador'} avatar={creatorProfile?.avatar||creator?.avatar} size={70}/><span className="k2-eyebrow">ESPACIO DEL CREADOR</span><h1>{creatorProfile?.name||creator?.creator||'Perfil del creador'}</h1><p>{creatorProfile?.bio}</p><p>{creatorProfile?.postCount||0} publicaciones</p>{creatorId===user?.id?<div className="k2-row"><button className="k2-primary" onClick={()=>navigate('/profile')}><Pencil size={16}/>Editar mi perfil</button><button className="k2-secondary" onClick={()=>navigate('/studio/upload')}><Plus size={16}/>Publicar</button></div>:<button className="k2-primary" onClick={()=>social('follow',creatorId)}>{account.following.includes(creatorId)?'Siguiendo':'Seguir creador'}</button>}</div>}
      <div className="k2-section-heading" id="feed-content"><div><span className="k2-eyebrow">{studio?'TU ESTUDIO':'TU COMUNIDAD, EN UN SOLO LUGAR'}</span><h1>{studio?'Mis publicaciones':savedView?'Publicaciones guardadas':followingView?'Creadores que sigues':creatorId?'Publicaciones':'El muro de KeyTube'}</h1><p>{studio?'Todo lo que compartes con tu comunidad.':'Descubre lo que comparten los creadores. Un adelanto, una nueva conexión.'}</p></div></div>
      {(!creatorId||creatorId===user?.id)&&!savedView&&!followingView&&<div className="k2-composer"><div><button className="k2-composer-avatar" aria-label="Ir a mi perfil" onClick={()=>{if(needUser())navigate('/profile');}}><CreatorAvatar name={account.profile?.name||user?.name||'Tú'} avatar={account.profile?.avatar} size={44}/></button><button className="k2-composer-prompt" onClick={()=>{if(needUser())navigate('/studio/upload');}}>¿Qué quieres compartir{user?', '+(account.profile?.name||user.name).split(' ')[0]:''}?</button></div><div className="k2-composer-types">{[{label:'Video',icon:Play},{label:'Foto',icon:ImageIcon},{label:'Música',icon:Headphones},{label:'Documento',icon:FileText}].map(t=><button key={t.label} onClick={()=>{if(needUser())navigate('/studio/upload?type='+({Video:'video',Foto:'image',Música:'audio',Documento:'document'}[t.label]));}}><t.icon size={18}/>{t.label}</button>)}</div></div>}
      <div className="k2-feed-controls"><label><ArrowDownWideNarrow size={17}/><span className="k2-sort-label">Ordenar</span><select aria-label="Ordenar publicaciones por fecha" value={order} onChange={e=>setOrder(e.target.value as 'asc'|'desc')}><option value="desc">Más recientes · descendente</option><option value="asc">Más antiguas · ascendente</option></select></label><button className="k2-refresh" onClick={()=>void refreshPosts()} disabled={loading}><RefreshCw size={16} className={loading?'k2-spin':''}/>Actualizar</button></div>
      <div className="k2-filter-row">{filters.map(f=><button key={f.name} className={filter===f.name?'active':''} onClick={()=>setFilter(f.name)}><f.icon size={16}/>{f.name}</button>)}<select aria-label="Filtrar categoría" value={CATEGORIES.slice(5).includes(filter)?filter:''} onChange={e=>setFilter(e.target.value||'Todos')}><option value="">Categorías</option>{CATEGORIES.slice(5).map(c=><option key={c}>{c}</option>)}</select><label className="k2-free-toggle"><input type="checkbox" checked={freeOnly} onChange={e=>setFreeOnly(e.target.checked)}/>Solo gratis</label></div>
      {feedError&&<p className="k2-error" role="alert">{feedError}</p>}
      {loading?<div className="k2-empty"><LoaderCircle className="k2-spin"/><p>Cargando publicaciones…</p></div>:filtered.length?<div className="k2-feed-stream">{filtered.map(p=><FeedPost key={p.id} post={p} own={p.creator_id===user?.id} saved={account.saved.includes(p.id)} onOpen={()=>navigate('/content/'+p.id)} onCreator={()=>navigate('/creator/'+p.creator_id)} onSave={()=>social('save',p.id)} onDelete={()=>setDeletePost(p)} onManage={()=>setManagePost(p)} onNotice={setToast}/>)}</div>:!feedError&&<div className="k2-empty"><Upload size={38}/><h2>{search||filter!=='Todos'||freeOnly?'No encontramos publicaciones con estos filtros':savedView?'Guarda lo que te inspire':followingView?'Tu comunidad empieza aquí':'Este espacio espera tu primera publicación'}</h2><p>{savedView?'Usa Guardar en una publicación y la encontrarás aquí.':followingView?'Sigue a otros creadores desde sus perfiles para ver aquí lo que comparten.':'Los videos, fotos, documentos y canciones que publiques aparecerán en este muro.'}</p><div className="k2-row"><button className="k2-primary" onClick={()=>{if(needUser())navigate('/studio/upload');}}><Plus size={16}/>Crear publicación</button>{(search||filter!=='Todos'||freeOnly||savedView||followingView)&&<button className="k2-secondary" onClick={()=>{setFilter('Todos');setFreeOnly(false);setSearch('');navigate('/');}}>Ver todo el muro</button>}</div></div>}
      {hasMore&&!loading&&<div className="k2-load-more"><button className="k2-secondary" disabled={loadingMore} onClick={()=>void loadMore()}>{loadingMore?<LoaderCircle className="k2-spin" size={17}/>:<Plus size={17}/>} {loadingMore?'Cargando…':'Cargar más publicaciones'}</button></div>}
      {!hasMore&&!loading&&!!filtered.length&&<p className="k2-feed-end">Ya viste todas las publicaciones de esta selección.</p>}
      {creatorId&&!!creatorPlans.length&&<section className="k2-creator-plans"><h2>Membresías de {creatorProfile?.name||creator?.creator}</h2>{renderPlans(creatorPlans,false)}<p>Abre una publicación para elegir el plan que la desbloquea.</p></section>}
    </section><aside className="k2-discover-aside">
      {user&&<div className="k2-my-profile"><CreatorAvatar name={account.profile?.name||user.name} avatar={account.profile?.avatar} size={54}/><h3>{account.profile?.name||user.name}</h3><p>{account.postCount} publicaciones · {myPlans.length} planes</p><button className="k2-secondary" onClick={()=>navigate('/profile')}><Pencil size={15}/>Editar mi perfil</button><button className="k2-text-button" onClick={()=>navigate('/creator/'+user.id)}>Ver mi perfil público →</button></div>}
      {!!posts.length&&<div className="k2-creators-list"><h3>En este muro</h3>{Array.from(new Map(posts.map(p=>[p.creator_id,p])).values()).slice(0,5).map(p=><button key={p.creator_id} onClick={()=>navigate('/creator/'+p.creator_id)}><CreatorAvatar name={p.creator} avatar={p.avatar}/><span><strong>{p.creator}</strong><small>{p.category}</small></span><ArrowRight size={16}/></button>)}</div>}
      <div className="k2-community-card"><span className="k2-large-lock"><KeyRound size={28}/></span><h2>Tu contenido.<br/>Tu valor.</h2><p>Publica gratis o crea dos planes de membresía para tu comunidad.</p><button className="k2-secondary" onClick={()=>{if(needUser())navigate('/memberships');}}>Gestionar mis planes<ArrowRight size={15}/></button></div>
    </aside></div>}
    </main><footer className="k2-footer"><Brand/><span>Tu contenido. Tu comunidad. Tu llave.</span><a href="https://unlock-protocol.com" target="_blank" rel="noreferrer">Conoce Unlock ↗</a></footer></div>
    <WalletConnector/>
    {auth&&<Modal title="Acceso a KeyTube" onClose={()=>setAuth(false)}>{error&&<p className="k2-error" role="alert">{error}</p>}<AuthForm googleEnabled={google} onSuccess={()=>{setAuth(false);refreshAccount().catch(e=>setError(errorText(e)));setToast('Ya estás en KeyTube.');}}/></Modal>}
    {managePost&&<PostSettings key={managePost.id} post={managePost} plans={myPlans} onClose={()=>setManagePost(null)} onSaved={async updated=>{setFull(null);if(post?.id===updated.id){setPost(updated);setFull(await api<FullContent>('/api/studio?post='+updated.id));}setManagePost(null);await refreshPosts();await refreshAccount();setToast(updated.status==='hidden'?'Publicación oculta. Solo tú puedes verla en Mi contenido.':'Acceso de la publicación actualizado.');}}/>}
    {deletePost&&<Modal title="Eliminar publicación" onClose={()=>{if(!deleting)setDeletePost(null);}}><h2>¿Eliminar esta publicación?</h2><p>«{deletePost.title}» dejará de estar disponible para tus visitantes y miembros.</p>{deleteError&&<p className="k2-error" role="alert">{deleteError}</p>}<div className="k2-row"><button className="k2-secondary" disabled={deleting} onClick={()=>setDeletePost(null)}>Cancelar</button><button className="k2-primary" disabled={deleting} onClick={async()=>{setDeleting(true);try{await api('/api/studio?post='+deletePost.id,undefined,'DELETE');if(contentId===deletePost.id){setPost(null);setFull(null);navigate('/studio');}setDeletePost(null);await refreshPosts();await refreshAccount();setToast('Publicación eliminada.');}catch(e){setDeleteError(errorText(e));}finally{setDeleting(false);}}}>Eliminar</button></div></Modal>}
    {toast&&<div className="k2-toast" role="status"><Check size={18}/>{toast}</div>}
  </div>;
}
