import assert from 'node:assert/strict';
import {toHex} from 'viem';
import {startWalletDiscovery,openWalletConnection,cancelWalletConnection,getWalletState,chooseWallet,signWalletMessage,disconnectWallet,requireWalletAccount,walletError} from '../lib/wallet-connection.ts';
globalThis.window=new EventTarget();
const address='0x1111111111111111111111111111111111111111',second='0x2222222222222222222222222222222222222222';
let count=0;const ok=s=>{count++;console.log('PASS',s);};
const stop=startWalletDiscovery();
let flow=openWalletConnection();assert.equal(getWalletState().open,true);assert.equal(getWalletState().wallets.length,0);
cancelWalletConnection();await assert.rejects(flow,{code:'WALLET_CANCELLED'});
ok('Connection opens an actionable dialog even without an extension and cancellation settles the request');
const calls=[],events=new Map();let accounts=[address],reject=false;
const provider={request:async args=>{calls.push(args);if(reject)throw {code:4001};if(args.method==='personal_sign')return '0x1234';return accounts;},on:(name,handler)=>events.set(name,handler),removeListener:name=>events.delete(name)};
window.addEventListener('eip6963:requestProvider',()=>window.dispatchEvent(new CustomEvent('eip6963:announceProvider',{detail:{info:{uuid:'wallet-1',name:'My wallet'},provider}})));
window.ethereum={request:async()=>{throw new Error('The wrong wallet was used');},isMetaMask:true};
flow=openWalletConnection();assert.equal(getWalletState().wallets.length,2);
await chooseWallet('eip6963-wallet-1');assert.equal(await flow,address);assert.equal(getWalletState().open,false);
assert.equal(await signWalletMessage(address,'KeyTube prueba'),'0x1234');
assert.deepEqual(calls.at(-2),{method:'personal_sign',params:[toHex('KeyTube prueba'),address]});
ok('Multiple wallets are discovered and account requests and signatures use the selected provider');
accounts=[second];events.get('accountsChanged')(accounts);assert.equal(getWalletState().address,second);
await assert.rejects(requireWalletAccount(address),{code:'WALLET_ACCOUNT_CHANGED'});
events.get('accountsChanged')([]);assert.equal(getWalletState().address,null);
ok('Account switching and disconnection invalidate the previous identity');
flow=openWalletConnection();reject=true;await chooseWallet('eip6963-wallet-1');assert.match(getWalletState().error,/Cancelaste/);assert.equal(getWalletState().requestingId,null);
reject=false;await chooseWallet('eip6963-wallet-1');assert.equal(await flow,second);
assert.match(walletError({code:-32002}).message,/pendiente/);
ok('Rejected and already-pending requests show clear feedback and allow retry');
let resolve;const slow={request:()=>new Promise(r=>{resolve=r;})};
window.dispatchEvent(new CustomEvent('eip6963:announceProvider',{detail:{info:{uuid:'slow',name:'Slow'},provider:slow}}));
flow=openWalletConnection();const pending=chooseWallet('eip6963-slow');await Promise.resolve();cancelWalletConnection();await assert.rejects(flow,{code:'WALLET_CANCELLED'});resolve([address]);await pending;assert.equal(getWalletState().address,null);
ok('A late extension response cannot reconnect a cancelled wallet flow');
disconnectWallet();stop();delete globalThis.window;
console.log(`${count} wallet checks passed using simulated browser extension providers.`);
