"use client";
import {useState,useEffect,useCallback,type FormEvent} from 'react';
import {usePathname,useRouter} from 'next/navigation';
import {Home,Compass,Bookmark,Users,Upload,KeyRound,Settings,LogOut,Search,Play,Headphones,Image as ImageIcon,FileText,ArrowRight,LockKeyhole,Check,Plus,Menu,Trash2,ExternalLink,Wallet,LoaderCircle,Sparkles,MessageCircle,Eye,ArrowDownUp} from 'lucide-react';
import type {Address} from 'viem';
import {Brand,CreatorAvatar,ContentCard,ContentMedia} from '@/components/keytube-content';
import {Modal,AuthForm,PlanEditor,Publisher,ProfileEditor} from '@/components/keytube-forms';
import {api,connectWallet,walletNetwork,signProof,checkoutUrl,errorText,shortAddress,mediaLabels} from '@/lib/keytube-client';
import {CATEGORIES,type PublicPost,type FullContent,type CreatorPlan,type Membership} from '@/lib/keytube-types';
import './keytube-v2.css';
type User={id:string;name:string;email?:string};
type Account={profile:{name:string;bio:string;avatar:string;wallet:string}|null;saved:string[];following:string[];postCount:number};
type Comment={id:string;name:string;body:string;created_at:number};
const emptyAccount:Account={profile:null,saved:[],following:[],postCount:0};
const filters=[{name:'Todos',icon:Compass},{name:'Videos',icon:Play},{name:'Imágenes',icon:ImageIcon},{name:'Audio',icon:Headphones},{name:'Documentos',icon:FileText}];
const typeFilter:Record<string,string>={Videos:'video',Imágenes:'image',Audio:'audio',Documentos:'document'};
type SortMode='newest'|'oldest'|'views_desc'|'views_asc';
export default function KeyTubeV2({user:initialUser}:{user:User|null;signInUrl?:string}) {
  const router=useRouter(),path=usePathname();
  const [user,setUser]=useState(initialUser),[account,setAccount]=useState<Account>(emptyAccount),[posts,setPosts]=useState<PublicPost[]>([]),[myPlans,setMyPlans]=useState<CreatorPlan[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[toast,setToast]=useState(''),[auth,setAuth]=useState(!initialUser),[google,setGoogle]=useState(false),[mobile,setMobile]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('Todos'),[freeOnly,setFreeOnly]=useState(false),[sort,setSort]=useState<SortMode>('newest'),[wallet,setWallet]=useState<Address|null>(null);
  const [post,setPost]=useState<PublicPost|null>(null),[full,setFull]=useState<FullContent|null>(null),[creatorPlans,setCreatorPlans]=useState<CreatorPlan[]>([]),[purchase,setPurchase]=useState(false),[verifying,setVerifying]=useState(false),[comments,setComments]=useState<Comment[]>([]),[comment,setComment]=useState(''),[commentBusy,setCommentBusy]=useState(false),[legacyQuote,setLegacyQuote]=useState<Membership|null>(null),[deletePost,setDeletePost]=useState<PublicPost|null>(null),[deleting,setDeleting]=useState(false);
  const studio=path.startsWith('/studio'),upload=path==='/studio/upload',planView=path==='/memberships',profileView=path==='/profile',savedView=path==='/saved',followingView=path==='/following',contentId=path.startsWith('/content/')?decodeURIComponent(path.split('/')[2]):null,creatorId=path.startsWith('/creator/')?decodeURIComponent(path.split('/')[2]):null;
  const navigate=(url:string)=>{setMobile(false);setError('');router.push(url);};
  const refreshAccount=useCallback(async()=>{const [s,a]=await Promise.all([api<{user:User|null;googleEnabled:boolean}>('/api/auth/session'),api<Account>('/api/account')]);setUser(s.user);setGoogle(s.googleEnabled);setAccount(a);return s.user;},[]);
  const refreshPosts=useCallback(async()=>{const r=await api<{posts:PublicPost[]}>('/api/posts');setPosts(r.posts);},[]);
  const refreshPlans=useCallback(async()=>{const r=await api<{plans:CreatorPlan[]}>('/api/plans');setMyPlans(r.plans);},[]);
  useEffect(()=>{Promise.all([refreshAccount(),refreshPosts()]).catch(e=>setError(errorText(e))).finally(()=>setLoading(false));const params=new URLSearchParams(window.location.search);if(params.has('authError')){setAuth(true);const code=params.get('authError');setError(code==='use_password'?'Ese correo ya tiene una cuenta. Inicia sesión con tu contraseña.':code==='google_unavailable'?'Google todavía no está configurado en este proyecto.':'No se completó el acceso con Google. Puedes volver a intentarlo.');}if(params.has('login'))setAuth(true);},[refreshAccount,refreshPosts]);
  useEffect(()=>{if(user)refreshPlans().catch(e=>setError(errorText(e)));else setMyPlans([]);},[user?.id,refreshPlans]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t);},[toast]);
  useEffect(()=>{const changed=()=>{setWallet(null);setFull(null);};window.ethereum?.on?.('accountsChanged',changed);window.ethereum?.on?.('chainChanged',changed);return()=>{window.ethereum?.removeListener?.('accountsChanged',changed);window.ethereum?.removeListener?.('chainChanged',changed);};},[]);
  useEffect(()=>{if(!full?.expiresAt)return;const t=setTimeout(()=>{setFull(null);setToast('Vuelve a verificar tu membresía para continuar.');},Math.max(0,full.expiresAt-Date.now()));return()=>clearTimeout(t);},[full]);
  useEffect(()=>{
    let active=true;setFull(null);setPurchase(false);setPost(null);setComments([]);setCreatorPlans([]);setLegacyQuote(null);
    if(!contentId)return;
    const get=api<{post:PublicPost}>(`/api/posts?id=${encodeURIComponent(contentId)}&track=1`);
    get.then(async r=>{if(!active)return;setPost(r.post);
      setPosts(current=>current.map(p=>p.id===r.post.id?r.post:p));
      const jobs:Promise<void>[]=[];
      if(r.post.visibility==='free')jobs.push(api<FullContent>(`/api/free-content?post=${r.post.id}`).then(d=>{if(active)setFull(d);}));
      jobs.push(api<{plans:CreatorPlan[]}>(`/api/plans?creator=${encodeURIComponent(r.post.creator_id||'')}`).then(d=>{if(active)setCreatorPlans(d.plans);}));
      if(r.post.lock&&!r.post.plan_id)jobs.push(api<Membership>(`/api/membership?post=${r.post.id}`).then(d=>{if(active)setLegacyQuote(d);}));
      jobs.push(api<{comments:Comment[]}>(`/api/comments?post=${r.post.id}`).then(d=>{if(active)setComments(d.comments);}));
      await Promise.all(jobs);
    }).catch(e=>{if(active)setError(errorText(e));});return()=>{active=false;};
  },[contentId]);
  useEffect(()=>{if(!creatorId)return;let active=true;api<{plans:CreatorPlan[]}>(`/api/plans?creator=${encodeURIComponent(creatorId)}`).then(d=>{if(active)setCreatorPlans(d.plans);}).catch(e=>setError(errorText(e)));return()=>{active=false;};},[creatorId]);
  function needUser(){if(user)return true;setAuth(true);return false;}
  async function social(kind:'save'|'follow',target:string){if(!needUser())return;try{const list=kind==='save'?account.saved:account.following,active=!list.includes(target);await api('/api/social',{kind,target,active});await refreshAccount();setToast(kind==='save'?(active?'Publicación guardada':'Publicación eliminada de guardados'):(active?'Ahora sigues a este creador':'Dejaste de seguir a este creador'));}catch(e){setError(errorText(e));}}
  async function verify(){if(!post)return;setVerifying(true);setError('');try{const address=await connectWallet();setWallet(address);const proof=await signProof('read',address,post.network,{postId:post.id});const data=await api<FullContent>('/api/access',{postId:post.id,...proof});setFull(data);setPurchase(false);setToast('Membresía válida. Ya puedes disfrutar el contenido completo.');}catch(e){setError(errorText(e));setPurchase(true);}finally{setVerifying(false);}}
  async function buy(plan?:CreatorPlan){if(!post||!needUser())return;try{window.location.assign(checkoutUrl(plan?{...post,lock:plan.lock,network:plan.network}:post));}catch(e){setError(errorText(e));}}
  async function addComment(e:FormEvent){e.preventDefault();if(!post||!needUser())return;setCommentBusy(true);try{const r=await api<{comment:Comment}>('/api/comments',{postId:post.id,body:comment});setComments(c=>[r.comment,...c]);setComment('');}catch(e){setError(errorText(e));}finally{setCommentBusy(false);}}
  async function linkWallet(){if(!needUser())return;try{const address=await connectWallet({chooseAccount:true});const network=await walletNetwork();const proof=await signProof('wallet',address,network,{});await api('/api/wallet',{...proof,network});setWallet(address);await refreshAccount();setToast('Wallet vinculada a tu perfil.');}catch(e){setError(errorText(e));}}
  async function logout(){try{await api('/api/auth/logout',{});setUser(null);setAccount(emptyAccount);setFull(null);setWallet(null);setMyPlans([]);navigate('/');setToast('Sesión cerrada.');}catch(e){setError(errorText(e));}}
  const mine=posts.filter(p=>p.creator_id===user?.id),creatorPosts=posts.filter(p=>p.creator_id===creatorId),creator=creatorPosts[0];
  const visible=(studio?mine:creatorId?creatorPosts:savedView?posts.filter(p=>account.saved.includes(p.id)):followingView?posts.filter(p=>account.following.includes(p.creator_id||'')):posts).filter(p=>(!freeOnly||p.visibility==='free')&&(filter==='Todos'||typeFilter[filter]===p.type||p.category===filter)&&`${p.title} ${p.creator} ${p.category}`.toLowerCase().includes(search.toLowerCase()));
  const filtered=[...visible].sort((a,b)=>sort==='oldest'?a.created_at-b.created_at:sort==='views_desc'?(b.views||0)-(a.views||0)||b.created_at-a.created_at:sort==='views_asc'?(a.views||0)-(b.views||0)||b.created_at-a.created_at:b.created_at-a.created_at);
  const locked=!!post&&!full&&post.visibility!=='free';
  const eligible=creatorPlans.filter(p=>post&&(p.lock.toLowerCase()===post.lock.toLowerCase()||p.lock.toLowerCase()===post.premium_lock?.toLowerCase()));
  const renderPlans=(items:CreatorPlan[],buyButtons:boolean)=> <div className="k2-plan-grid">{items.map(p=><article className={`k2-plan-card ${p.slot==='premium'?'premium':''}`} key={p.id}><span className="k2-badge"><KeyRound size={13}/>{p.slot==='basic'?'Básico':'Premium'}</span><h2>{p.name}</h2><p>{p.description}</p><div className="k2-price">{p.quote?`${p.quote.price} ${p.quote.currency}`:'Precio por confirmar'}<small>{p.quote?p.quote.duration:`${p.durationDays} días`}</small></div><ul>{p.slot==='premium'&&<li><Check size={16}/>Todo el contenido del Básico</li>}{p.benefits.map((b,i)=><li key={i}><Check size={16}/>{b}</li>)}<li><Check size={16}/>{p.coverage.map(t=>mediaLabels[t]).join(' · ')}</li></ul><small>{p.network===84532||p.network===11155111?'Red de pruebas · sin cobros reales':'El pago se realiza en la red del plan'}</small>{buyButtons&&<button className="k2-primary" onClick={()=>buy(p)}>Comprar {p.name}<ArrowRight size={16}/></button>}</article>)}</div>;
  const card=(p:PublicPost,index:number)=><div key={p.id} className="k2-feed-item"><ContentCard post={p} index={index+1} saved={account.saved.includes(p.id)} onOpen={()=>navigate('/content/'+p.id)} onSave={()=>social('save',p.id)} onCreator={()=>navigate('/creator/'+(p.creator_id||''))}/>{studio&&<button className="k2-delete" onClick={()=>setDeletePost(p)}><Trash2 size={14}/> Eliminar publicación</button>}</div>;
  return <div className="k2-app"><aside className={`k2-sidebar ${mobile?'open':''}`}><button className="k2-brand-link" onClick={()=>navigate('/')} aria-label="KeyTube inicio"><Brand/></button><nav aria-label="Principal">{[{url:'/',label:'Inicio',icon:Home},{url:'/explore',label:'Explorar',icon:Compass},{url:'/saved',label:'Guardados',icon:Bookmark},{url:'/following',label:'Siguiendo',icon:Users}].map(n=><button key={n.url} className={path===n.url?'active':''} onClick={()=>navigate(n.url)}><n.icon size={19}/>{n.label}</button>)}<span className="k2-nav-caption">TU ESTUDIO</span>{[{url:'/studio',label:'Mi contenido',icon:Play},{url:'/studio/upload',label:'Subir contenido',icon:Upload},{url:'/memberships',label:'Mis planes',icon:KeyRound},{url:'/profile',label:'Mi cuenta',icon:Settings}].map(n=><button key={n.url} className={path===n.url?'active':''} onClick={()=>{if(needUser())navigate(n.url);}}><n.icon size={19}/>{n.label}</button>)}</nav><div className="k2-sidebar-card"><Sparkles size={26}/><strong>Tu talento tiene valor.</strong><p>Comparte lo que creas. Construye tu comunidad.</p><button className="k2-primary" onClick={()=>{if(needUser())navigate('/studio/upload');}}>Empezar a crear</button></div><span className="k2-powered"><LockKeyhole size={15}/> Membresías con <strong>Unlock</strong></span></aside>
    <div className="k2-page"><header className="k2-topbar"><button className="k2-icon k2-mobile-menu" aria-label="Abrir menú" onClick={()=>setMobile(!mobile)}><Menu size={22}/></button><label className="k2-search"><Search size={19}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Busca creadores, contenido o categorías…" aria-label="Buscar contenido"/></label><div className="k2-top-actions">{user?<><button className="k2-secondary k2-upload-button" onClick={()=>navigate('/studio/upload')}><Plus size={17}/> Crear</button><button className="k2-user" onClick={()=>navigate('/profile')}><CreatorAvatar name={account.profile?.name||user.name} avatar={account.profile?.avatar}/><span>{account.profile?.name||user.name}</span></button></>:<><button className="k2-secondary" onClick={()=>setAuth(true)}>Iniciar sesión</button><button className="k2-primary" onClick={()=>setAuth(true)}>Crear cuenta</button></>}</div></header>
    <main className="k2-main">{error&&<div className="k2-error k2-global-error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Cerrar mensaje">×</button></div>}
    {(studio||planView||profileView)&&!user?<div className="k2-empty"><KeyRound size={40}/><h1>Entra a tu cuenta para continuar</h1><p>Crea tu perfil y empieza a compartir contenido.</p><button className="k2-primary" onClick={()=>setAuth(true)}>Iniciar sesión o registrarme</button></div>:
    contentId?<>{post?<div className="k2-content-layout"><section><button className="k2-back" onClick={()=>navigate('/')}>← Volver a explorar</button><div className="k2-media-wrap"><ContentMedia post={post} full={full} onPreviewEnd={()=>setPurchase(true)} onError={()=>{setFull(null);setError('No se pudo reproducir el archivo. Si tu acceso venció, vuelve a verificar tu membresía.');}}/>{locked&&purchase&&<div className="k2-player-gate"><span className="k2-large-lock"><LockKeyhole size={30}/></span><h2>Esto es solo el comienzo.</h2><p>El adelanto terminó. Hazte miembro para disfrutar el contenido completo.</p><button className="k2-primary" onClick={()=>document.getElementById('buy-plans')?.scrollIntoView({behavior:'smooth'})}>Ver membresías<ArrowRight size={17}/></button></div>}</div>
      <div className="k2-post-heading"><span className={`k2-badge ${full?'free':''}`}>{full?<><Check size={12}/> Contenido completo</>:post.visibility==='free'?'Gratis':<><LockKeyhole size={12}/> Adelanto gratis</>}</span><h1>{post.title}</h1><div className="k2-post-meta"><span><Eye size={14}/>{post.views||0} vistas</span><span>{new Date(post.created_at).toLocaleDateString('es')}</span></div><div className="k2-row"><button className="k2-creator-button" onClick={()=>navigate('/creator/'+post.creator_id)}><CreatorAvatar name={post.creator} avatar={post.avatar}/><span><strong>{post.creator}</strong><small>{post.category} · {mediaLabels[post.type||'text']}</small></span></button><button className="k2-secondary" onClick={()=>social('follow',post.creator_id||'')}>{account.following.includes(post.creator_id||'')?'Siguiendo':'Seguir'}</button><button className="k2-icon" aria-label="Guardar publicación" onClick={()=>social('save',post.id)}><Bookmark fill={account.saved.includes(post.id)?'currentColor':'none'} size={19}/></button>{user?.id===post.creator_id&&<button className="k2-delete k2-delete-detail" onClick={()=>setDeletePost(post)}><Trash2 size={14}/> Eliminar</button>}</div><p>{post.intro}</p>{full?.body&&<div className="k2-full-text">{full.body}</div>}</div>
      {locked&&<section id="buy-plans" className="k2-access-panel"><span className="k2-eyebrow">TU LLAVE AL CONTENIDO COMPLETO</span><h2>Elige cómo apoyar a {post.creator}</h2><p>Cada membresía pertenece a este creador. El acceso se comprueba con tu Key de Unlock.</p>{renderPlans(eligible,true)}{!eligible.length&&<div className="k2-notice"><p>{legacyQuote?`${legacyQuote.name} · ${legacyQuote.price} ${legacyQuote.currency} · ${legacyQuote.duration}`:'El precio y la duración se muestran al abrir Unlock.'}</p><button className="k2-primary" onClick={()=>buy()}>Comprar membresía<ExternalLink size={16}/></button></div>}<button className="k2-secondary k2-verify" disabled={verifying} onClick={verify}>{verifying?<LoaderCircle size={17} className="k2-spin"/>:<Wallet size={17}/>} {verifying?'Verificando membresía…':'Ya tengo membresía · verificar acceso'}</button><small>La compra se abre en Unlock. KeyTube no te pide MetaMask para navegar; solo necesitarás una wallet cuando quieras verificar una membresía Web3.</small>{user?.id===post.creator_id&&<button className="k2-secondary" onClick={async()=>{try{setFull(await api<FullContent>('/api/studio?post='+post.id));setPurchase(false);setToast('Vista privada del creador.');}catch(e){setError(errorText(e));}}}>Ver mi archivo completo</button>}</section>}
      <section className="k2-comments"><h2><MessageCircle size={20}/> Comentarios <span>{comments.length}</span></h2><form onSubmit={addComment}><input value={comment} onChange={e=>setComment(e.target.value)} minLength={2} maxLength={1000} required placeholder={user?'Comparte lo que te gustó…':'Inicia sesión para comentar'}/><button className="k2-primary" disabled={commentBusy}>Publicar</button></form>{comments.map(c=><article key={c.id}><CreatorAvatar name={c.name}/><div><strong>{c.name}</strong><small>{new Date(c.created_at).toLocaleDateString('es')}</small><p>{c.body}</p></div></article>)}{!comments.length&&<p>Sé la primera persona en comentar.</p>}</section></section><aside className="k2-related"><h3>Sigue descubriendo</h3>{posts.filter(p=>p.id!==post.id).slice(0,4).map(card)}</aside></div>:<div className="k2-empty"><LoaderCircle className="k2-spin"/><p>Cargando publicación…</p></div>}</>:
    upload?<><div className="k2-section-heading"><div><span className="k2-eyebrow">TU ESTUDIO CREATIVO</span><h1>Comparte algo extraordinario.</h1><p>Tu contenido, tus reglas. Decide qué muestras y qué desbloquean tus miembros.</p></div></div><Publisher creator={account.profile?.name||user!.name} plans={myPlans} onPublished={p=>{setToast('Tu publicación ya está disponible.');refreshPosts().catch(e=>setError(errorText(e)));refreshAccount().catch(e=>setError(errorText(e)));navigate('/content/'+p.id);}}/></>:
    planView?<><div className="k2-section-heading"><div><span className="k2-eyebrow">MONETIZA TU COMUNIDAD</span><h1>Dos planes. Tú decides el valor.</h1><p>Elige tu precio, duración y beneficios. KeyTube crea o vincula un Lock real de Unlock con tu propia wallet.</p></div><a className="k2-secondary" href="https://app.unlock-protocol.com/locks" target="_blank" rel="noreferrer">Panel de Unlock<ExternalLink size={16}/></a></div><div className="k2-wallet-panel"><div><Wallet size={20}/><span><strong>Wallet del creador</strong><small>{account.profile?.wallet?shortAddress(account.profile.wallet):'Todavía no vinculada'}</small></span></div><button className="k2-secondary" onClick={linkWallet}>{account.profile?.wallet?'Cambiar wallet del creador':'Conectar wallet para administrar planes'}</button></div><div className="k2-notice"><KeyRound size={20}/><span>La wallet solo se usa aquí para crear o modificar tus planes en Unlock. Navegar, editar tu perfil y subir contenido no necesita MetaMask.</span></div><div className="k2-plan-grid">{(['basic','premium'] as const).map(slot=><PlanEditor key={`${slot}-${myPlans.find(p=>p.slot===slot)?.id||'new'}`} slot={slot} existing={myPlans.find(p=>p.slot===slot)} sibling={myPlans.find(p=>p.slot!==slot)} onSaved={()=>{refreshPlans().catch(e=>setError(errorText(e)));setToast('Plan conectado con Unlock.');}}/>)}</div></>:
    profileView?<><div className="k2-section-heading"><div><span className="k2-eyebrow">TU ESPACIO EN KEYTUBE</span><h1>Mi cuenta</h1><p>Edita tu nombre, biografía y foto de perfil desde cualquier dispositivo.</p></div></div><div className="k2-profile-card"><div className="k2-profile-summary"><CreatorAvatar name={account.profile?.name||user!.name} avatar={account.profile?.avatar} size={72}/><div><h2>{account.profile?.name||user!.name}</h2><p>{user?.email}</p></div></div><div className="k2-stats"><span><strong>{account.postCount}</strong>Publicaciones</span><span><strong>{myPlans.length}</strong>Planes</span><span><strong>{account.following.length}</strong>Siguiendo</span></div><ProfileEditor profile={account.profile} fallbackName={user!.name} onSaved={async()=>{await refreshAccount();setToast('Perfil actualizado.');}}/><div className="k2-profile-links"><a className="k2-secondary" href="https://app.unlock-protocol.com/locks" target="_blank" rel="noreferrer"><KeyRound size={17}/> Abrir panel de Unlock<ExternalLink size={15}/></a>{google&&<a className="k2-secondary" href="/api/auth/google/start?link=1">Vincular mi cuenta con Google</a>}<button className="k2-secondary" onClick={logout}><LogOut size={17}/> Cerrar sesión</button></div></div></>:
    <><div className="k2-feed-layout"><section className="k2-feed">{!studio&&!savedView&&!followingView&&!creatorId&&<div className="k2-hero"><div><span className="k2-eyebrow">EL CONTENIDO QUE TE CONECTA</span><h1>Lo que te apasiona,<br/>ahora tiene <em>llave.</em></h1><p>Descubre, disfruta y apoya a tus creadores.<br/>Un adelanto gratis. Un mundo por desbloquear.</p><button className="k2-primary" onClick={()=>document.getElementById('feed-content')?.scrollIntoView({behavior:'smooth'})}>Explorar contenido<ArrowRight size={17}/></button><span className="k2-hero-unlock"><LockKeyhole size={16}/> Powered by <strong>Unlock</strong></span></div></div>}
    {creatorId&&<div className="k2-creator-hero"><CreatorAvatar name={creator?.creator||'Creador'} avatar={creator?.avatar} size={70}/><span className="k2-eyebrow">ESPACIO DEL CREADOR</span><h1>{creator?.creator||'Creador'}</h1><p>{creatorPosts.length} publicaciones · Descubre su contenido y sus membresías.</p><button className="k2-primary" onClick={()=>social('follow',creatorId)}>{account.following.includes(creatorId)?'Siguiendo':'Seguir creador'}</button></div>}
    <div className="k2-section-heading" id="feed-content"><div><span className="k2-eyebrow">{studio?'TU ESTUDIO':'HECHO POR PERSONAS, PARA PERSONAS'}</span><h2>{studio?'Mi contenido':savedView?'Tus favoritos, siempre cerca':followingView?'De los creadores que sigues':creatorId?'Todas las publicaciones':'Descubre algo que te inspire'}</h2></div>{studio?<button className="k2-primary" onClick={()=>navigate('/studio/upload')}><Plus size={17}/> Publicar</button>:<label className="k2-free-toggle"><input type="checkbox" checked={freeOnly} onChange={e=>setFreeOnly(e.target.checked)}/>Solo gratis</label>}</div>
    <div className="k2-filter-row">{filters.map(f=><button key={f.name} className={filter===f.name?'active':''} onClick={()=>setFilter(f.name)}><f.icon size={16}/>{f.name}</button>)}<select aria-label="Filtrar categoría" value={CATEGORIES.slice(5).includes(filter)?filter:''} onChange={e=>setFilter(e.target.value||'Todos')}><option value="">Más categorías</option>{CATEGORIES.slice(5).map(c=><option key={c}>{c}</option>)}</select><label className="k2-sort"><ArrowDownUp size={14}/><select aria-label="Ordenar publicaciones" value={sort} onChange={e=>setSort(e.target.value as SortMode)}><option value="newest">Más recientes</option><option value="oldest">Más antiguas</option><option value="views_desc">Más vistas</option><option value="views_asc">Menos vistas</option></select></label></div>
    {loading?<div className="k2-empty"><LoaderCircle className="k2-spin"/><p>Cargando contenido…</p></div>:filtered.length?<div className="k2-grid">{filtered.map(card)}</div>:<div className="k2-empty"><Compass size={36}/><h2>{studio?'Tu primera publicación empieza aquí':'Todavía no hay publicaciones aquí'}</h2><p>{studio?'Comparte un video, una canción, tus imágenes o una idea.':'Prueba otra categoría o descubre nuevos creadores.'}</p><button className="k2-secondary" onClick={()=>{if(studio)navigate('/studio/upload');else{setFilter('Todos');setFreeOnly(false);setSearch('');navigate('/');}}}>{studio?'Subir contenido':'Explorar contenido'}</button></div>}
    {creatorId&&!!creatorPlans.length&&<section className="k2-creator-plans"><h2>Membresías de {creator?.creator}</h2>{renderPlans(creatorPlans,false)}<p>Abre una publicación para elegir el plan que la desbloquea.</p></section>}</section>
    {!studio&&<aside className="k2-discover-aside"><div className="k2-community-card"><span className="k2-large-lock"><KeyRound size={28}/></span><h2>Más contenido.<br/>Más cerca.</h2><p>Una membresía, una conexión directa con quienes te inspiran.</p><button className="k2-secondary" onClick={()=>{if(needUser())navigate('/memberships');}}>Crear mis planes<ArrowRight size={15}/></button></div><div className="k2-creators-list"><h3>Conoce a los creadores</h3>{Array.from(new Map(posts.map(p=>[p.creator_id,p])).values()).slice(0,5).map(p=><button key={p.creator_id} onClick={()=>navigate('/creator/'+p.creator_id)}><CreatorAvatar name={p.creator} avatar={p.avatar}/><span><strong>{p.creator}</strong><small>{p.category}</small></span><ArrowRight size={16}/></button>)}</div><div className="k2-tip"><Upload size={23}/><h3>También puedes crear.</h3><p>Publica gratis o comparte contenido exclusivo con tus miembros.</p><button onClick={()=>{if(needUser())navigate('/studio/upload');}}>Abrir mi estudio →</button></div></aside>}</div></>}
    </main><footer className="k2-footer"><Brand/><span>Tu contenido. Tu comunidad. Tu llave.</span><a href="https://unlock-protocol.com" target="_blank" rel="noreferrer">Conoce Unlock ↗</a></footer></div>
    {auth&&<Modal title="Acceso a KeyTube" onClose={()=>setAuth(false)}>{error&&<p className="k2-error" role="alert">{error}</p>}<AuthForm googleEnabled={google} onSuccess={()=>{setAuth(false);refreshAccount().catch(e=>setError(errorText(e)));setToast('Ya estás en KeyTube.');}}/></Modal>}
    {deletePost&&<Modal title="Eliminar publicación" onClose={()=>{if(!deleting)setDeletePost(null);}}><h2>¿Eliminar esta publicación?</h2><p>«{deletePost.title}» dejará de estar disponible para tus visitantes y miembros.</p><div className="k2-row"><button className="k2-secondary" disabled={deleting} onClick={()=>setDeletePost(null)}>Cancelar</button><button className="k2-primary" disabled={deleting} onClick={async()=>{setDeleting(true);try{const removedId=deletePost.id;await api('/api/studio?post='+removedId,undefined,'DELETE');setDeletePost(null);setPost(p=>p?.id===removedId?null:p);await refreshPosts();await refreshAccount();if(contentId===removedId)navigate('/studio');setToast('Publicación y sus archivos fueron eliminados.');}catch(e){setError(errorText(e));}finally{setDeleting(false);}}}>Eliminar</button></div></Modal>}
    {toast&&<div className="k2-toast" role="status"><Check size={18}/>{toast}</div>}
  </div>;
}
