"use client";

import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { usePathname, useRouter } from "next/navigation";
import {
  Home, Compass, Bookmark, Users, Upload, KeyRound, Settings, LogOut, Search,
  Play, Headphones, Image as ImageIcon, FileText, ArrowRight, LockKeyhole, Check,
  Plus, Menu, Trash2, ExternalLink, Wallet, LoaderCircle, Sparkles, TrendingUp,
  MessageCircle, Eye, ArrowDownUp, Unplug, Bell, History, FolderHeart, BarChart3,
  Heart, Share2, Flag, Ban, BadgeCheck, Link as LinkIcon, Shield, CheckCheck,
  CircleDollarSign, ListFilter, UserRoundCheck,
} from "lucide-react";
import type { Address } from "viem";
import { Brand, CreatorAvatar, ContentCard, ContentMedia } from "@/components/keytube-content";
import { Modal, AuthForm, PlanEditor, Publisher, ProfileEditor } from "@/components/keytube-forms";
import {
  api, connectWallet, connectedWallet, walletNetwork, signProof, checkoutUrl,
  errorText, shortAddress, mediaLabels,
} from "@/lib/keytube-client";
import {
  CATEGORIES, type PublicPost, type FullContent, type CreatorPlan, type Membership,
} from "@/lib/keytube-types";
import "./keytube-v2.css";

type User = { id: string; name: string; email?: string };
type Profile = {
  name: string; bio: string; avatar: string; cover?: string; website?: string;
  instagram?: string; youtube?: string; verified?: number; role?: string; wallet: string;
};
type Account = {
  isAdmin?: boolean; profile: Profile | null; saved: string[]; following: string[];
  liked: string[]; blocked: string[]; postCount: number; followerCount: number;
  collectionCount: number; unreadNotifications: number; accessCount: number;
};
type Comment = { id: string; owner_id?: string; name: string; body: string; parent_id?: string | null; created_at: number; avatar?: string; verified?: number };
type NotificationItem = { id:string; type:string; target_id:string|null; message:string; read_at:number|null; created_at:number; actor_name:string };
type HistoryItem = { post_id:string; progress:number; position_seconds:number; updated_at:number };
type CollectionItem = { id:string; name:string; item_count:number; created_at:number; updated_at:number };
type CollectionPost = { collection_id:string; post_id:string; title:string; creator:string };
type CreatorInfo = { profile:{ owner_id:string; name:string; bio:string; avatar:string; cover:string; website:string; instagram:string; youtube:string; verified:number; role:string; post_count:number; follower_count:number; total_views:number; total_likes:number }; following:boolean; blocked:boolean };
type StatsData = { summary:{posts:number;views:number;followers:number;accesses:number;comments:number;likes:number}; top:Array<{id:string;title:string;views:number;likes:number;comments:number;type:string;category:string}>; series:Array<{date:string;likes:number;comments:number;followers:number;accesses:number;total:number}>; period:number };
type AccessItem = { post_id:string;creator_id:string;title:string;creator:string;type:string;category:string;verified_at:number;network:number };
type ReportItem = { id:string;reporter_id:string;target_type:string;target_id:string;reason:string;details:string;status:string;created_at:number;reporter_name:string };

const emptyAccount: Account = { isAdmin:false, profile:null, saved:[], following:[], liked:[], blocked:[], postCount:0, followerCount:0, collectionCount:0, unreadNotifications:0, accessCount:0 };
const filters = [
  { name:"Todos", icon:Compass }, { name:"Videos", icon:Play }, { name:"Imágenes", icon:ImageIcon },
  { name:"Audio", icon:Headphones }, { name:"Documentos", icon:FileText },
];
const typeFilter: Record<string,string> = { Videos:"video", Imágenes:"image", Audio:"audio", Documentos:"document" };
type SortMode = "newest"|"oldest"|"views_desc"|"views_asc";
type FeedMode = "discover"|"forYou";

export default function KeyTubeV10({ user: initialUser }: { user: User | null; signInUrl?: string }) {
  const router=useRouter(), path=usePathname();
  const [user,setUser]=useState(initialUser),[account,setAccount]=useState<Account>(emptyAccount);
  const [posts,setPosts]=useState<PublicPost[]>([]),[recommended,setRecommended]=useState<PublicPost[]>([]),[myPlans,setMyPlans]=useState<CreatorPlan[]>([]);
  const [loading,setLoading]=useState(true),[error,setError]=useState(""),[toast,setToast]=useState(""),[auth,setAuth]=useState(!initialUser),[google,setGoogle]=useState(false),[recovery,setRecovery]=useState(false),[mobile,setMobile]=useState(false);
  const [search,setSearch]=useState(""),[filter,setFilter]=useState("Todos"),[accessFilter,setAccessFilter]=useState<"all"|"free"|"members">("all"),[sort,setSort]=useState<SortMode>("newest"),[feedMode,setFeedMode]=useState<FeedMode>(initialUser?"forYou":"discover"),[wallet,setWallet]=useState<Address|null>(null);
  const [post,setPost]=useState<PublicPost|null>(null),[full,setFull]=useState<FullContent|null>(null),[creatorPlans,setCreatorPlans]=useState<CreatorPlan[]>([]),[purchase,setPurchase]=useState(false),[verifying,setVerifying]=useState(false),[comments,setComments]=useState<Comment[]>([]),[comment,setComment]=useState(""),[replyTo,setReplyTo]=useState<Comment|null>(null),[commentBusy,setCommentBusy]=useState(false),[legacyQuote,setLegacyQuote]=useState<Membership|null>(null),[deletePost,setDeletePost]=useState<PublicPost|null>(null),[deleting,setDeleting]=useState(false),[resumePosition,setResumePosition]=useState(0);
  const [notifications,setNotifications]=useState<NotificationItem[]>([]),[history,setHistory]=useState<HistoryItem[]>([]),[collections,setCollections]=useState<CollectionItem[]>([]),[collectionPosts,setCollectionPosts]=useState<CollectionPost[]>([]),[collectionTarget,setCollectionTarget]=useState<PublicPost|null>(null),[newCollection,setNewCollection]=useState("");
  const [creatorInfo,setCreatorInfo]=useState<CreatorInfo|null>(null),[creatorTab,setCreatorTab]=useState("all"),[stats,setStats]=useState<StatsData|null>(null),[statsPeriod,setStatsPeriod]=useState<7|30|90>(30),[accesses,setAccesses]=useState<AccessItem[]>([]),[reports,setReports]=useState<ReportItem[]>([]);

  const studio=path.startsWith("/studio")&&!path.startsWith("/studio/stats"), upload=path==="/studio/upload", statsView=path==="/studio/stats", planView=path==="/memberships", profileView=path==="/profile", savedView=path==="/saved", followingView=path==="/following", notificationsView=path==="/notifications", historyView=path==="/history", collectionsView=path==="/collections", adminView=path==="/admin";
  const contentId=path.startsWith("/content/")?decodeURIComponent(path.split("/")[2]):null;
  const creatorId=path.startsWith("/creator/")?decodeURIComponent(path.split("/")[2]):null;
  const navigate=(url:string)=>{setMobile(false);setError("");router.push(url);};

  const refreshAccount=useCallback(async()=>{
    const [s,a]=await Promise.all([
      api<{user:User|null;googleEnabled:boolean;recoveryEnabled:boolean}>("/api/auth/session"),
      api<Account>("/api/account"),
    ]);
    setUser(s.user);setGoogle(s.googleEnabled);setRecovery(s.recoveryEnabled);setAccount(a);return s.user;
  },[]);
  const refreshPosts=useCallback(async()=>{const r=await api<{posts:PublicPost[]}>("/api/posts");setPosts(r.posts);},[]);
  const refreshRecommendations=useCallback(async()=>{try{const r=await api<{posts:PublicPost[]}>("/api/recommendations");setRecommended(r.posts);}catch{setRecommended([]);}},[]);
  const refreshPlans=useCallback(async()=>{const r=await api<{plans:CreatorPlan[]}>("/api/plans");setMyPlans(r.plans);},[]);
  const loadCollections=useCallback(async()=>{if(!user)return;const r=await api<{collections:CollectionItem[];items:CollectionPost[]}>("/api/collections");setCollections(r.collections);setCollectionPosts(r.items);},[user?.id]);

  useEffect(()=>{
    Promise.all([refreshAccount(),refreshPosts(),refreshRecommendations()]).catch(e=>setError(errorText(e))).finally(()=>setLoading(false));
    const params=new URLSearchParams(window.location.search);
    if(params.has("authError")){setAuth(true);const code=params.get("authError");setError(code==="use_password"?"Ese correo ya tiene una cuenta. Inicia sesión con tu contraseña.":code==="google_unavailable"?"Google todavía no está configurado.":"No se completó el acceso con Google.");}
    if(params.has("login"))setAuth(true);
  },[refreshAccount,refreshPosts,refreshRecommendations]);
  useEffect(()=>{if(user){refreshPlans().catch(e=>setError(errorText(e)));loadCollections().catch(()=>{});}else{setMyPlans([]);setRecommended([]);}},[user?.id,refreshPlans,loadCollections]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),4200);return()=>clearTimeout(t);},[toast]);
  useEffect(()=>{const changed=()=>{setWallet(null);setFull(null);};window.ethereum?.on?.("accountsChanged",changed);window.ethereum?.on?.("chainChanged",changed);return()=>{window.ethereum?.removeListener?.("accountsChanged",changed);window.ethereum?.removeListener?.("chainChanged",changed);};},[]);
  useEffect(()=>{connectedWallet().then(setWallet).catch(()=>setWallet(null));},[user?.id]);
  useEffect(()=>{if(!full?.expiresAt)return;const t=setTimeout(()=>{setFull(null);setToast("Vuelve a verificar tu membresía para continuar.");},Math.max(0,full.expiresAt-Date.now()));return()=>clearTimeout(t);},[full]);

  useEffect(()=>{
    let active=true;setFull(null);setPurchase(false);setPost(null);setComments([]);setCreatorPlans([]);setLegacyQuote(null);setResumePosition(0);
    if(!contentId)return;
    api<{post:PublicPost}>(`/api/posts?id=${encodeURIComponent(contentId)}&track=1`).then(async r=>{
      if(!active)return;setPost(r.post);setPosts(current=>current.map(p=>p.id===r.post.id?r.post:p));
      const jobs:Promise<unknown>[]=[];
      if(r.post.visibility==="free")jobs.push(api<FullContent>(`/api/free-content?post=${r.post.id}`).then(d=>active&&setFull(d)));
      jobs.push(api<{plans:CreatorPlan[]}>(`/api/plans?creator=${encodeURIComponent(r.post.creator_id||"")}`).then(d=>active&&setCreatorPlans(d.plans)));
      if(r.post.lock&&!r.post.plan_id)jobs.push(api<Membership>(`/api/membership?post=${r.post.id}`).then(d=>active&&setLegacyQuote(d)));
      jobs.push(api<{comments:Comment[]}>(`/api/comments?post=${r.post.id}`).then(d=>active&&setComments(d.comments)));
      if(user)jobs.push(api<{history:HistoryItem|null}>(`/api/history?post=${r.post.id}`).then(d=>active&&setResumePosition(d.history?.position_seconds||0)).catch(()=>{}));
      await Promise.all(jobs);
    }).catch(e=>active&&setError(errorText(e)));
    return()=>{active=false;};
  },[contentId,user?.id]);

  useEffect(()=>{
    if(!creatorId){setCreatorInfo(null);return;}let active=true;
    Promise.all([
      api<CreatorInfo>(`/api/creator?id=${encodeURIComponent(creatorId)}`),
      api<{plans:CreatorPlan[]}>(`/api/plans?creator=${encodeURIComponent(creatorId)}`),
    ]).then(([info,p])=>{if(active){setCreatorInfo(info);setCreatorPlans(p.plans);}}).catch(e=>active&&setError(errorText(e)));
    return()=>{active=false;};
  },[creatorId]);

  useEffect(()=>{
    if(!user)return;
    if(notificationsView)api<{notifications:NotificationItem[];unread:number}>("/api/notifications").then(r=>{setNotifications(r.notifications);setAccount(a=>({...a,unreadNotifications:r.unread}));}).catch(e=>setError(errorText(e)));
    if(historyView)api<{history:HistoryItem[]}>("/api/history").then(r=>setHistory(r.history)).catch(e=>setError(errorText(e)));
    if(collectionsView)loadCollections().catch(e=>setError(errorText(e)));
    if(statsView)api<StatsData>(`/api/stats?period=${statsPeriod}`).then(setStats).catch(e=>setError(errorText(e)));
    if(profileView)api<{accesses:AccessItem[]}>("/api/access-history").then(r=>setAccesses(r.accesses)).catch(()=>{});
    if(adminView&&account.isAdmin)api<{reports:ReportItem[]}>("/api/moderation").then(r=>setReports(r.reports)).catch(e=>setError(errorText(e)));
  },[user?.id,notificationsView,historyView,collectionsView,statsView,profileView,adminView,account.isAdmin,loadCollections]);

  function needUser(){if(user)return true;setAuth(true);return false;}
  async function social(kind:"save"|"follow"|"like",target:string){
    if(!needUser())return;
    try{
      const list=kind==="save"?account.saved:kind==="follow"?account.following:account.liked;
      const active=!list.includes(target);
      const r=await api<{active:boolean;likes?:number}>("/api/social",{kind,target,active});
      setAccount(a=>({...a,[kind==="save"?"saved":kind==="follow"?"following":"liked"]:active?[...list,target]:list.filter(x=>x!==target)}));
      if(kind==="like")setPosts(ps=>ps.map(p=>p.id===target?{...p,liked:active,likes:r.likes??Math.max(0,(p.likes||0)+(active?1:-1))}:p));
      if(kind==="follow")setCreatorInfo(info=>info&&info.profile.owner_id===target?{...info,following:active,profile:{...info.profile,follower_count:Math.max(0,info.profile.follower_count+(active?1:-1))}}:info);
      setToast(kind==="save"?(active?"Publicación guardada":"Quitada de guardados"):kind==="like"?(active?"Te gusta esta publicación":"Me gusta retirado"):(active?"Ahora sigues a este creador":"Dejaste de seguirlo"));
      refreshRecommendations().catch(()=>{});
    }catch(e){setError(errorText(e));}
  }
  async function share(p:PublicPost){const url=`${window.location.origin}/content/${p.id}`;try{if(navigator.share)await navigator.share({title:p.title,text:p.intro,url});else{await navigator.clipboard.writeText(url);setToast("Enlace copiado.");}}catch{/* cancel */}}
  async function trackProgress(postId:string,seconds:number,progress:number){if(!user)return;api("/api/history",{postId,positionSeconds:seconds,progress}).catch(()=>{});}
  async function verify(){if(!post)return;setVerifying(true);setError("");try{const address=await connectWallet();setWallet(address);const proof=await signProof("read",address,post.network,{postId:post.id});const data=await api<FullContent>("/api/access",{postId:post.id,...proof});setFull(data);setPurchase(false);setToast("Membresía válida. Contenido completo desbloqueado.");refreshAccount().catch(()=>{});}catch(e){setError(errorText(e));setPurchase(true);}finally{setVerifying(false);}}
  async function buy(plan?:CreatorPlan){if(!post||!needUser())return;try{const address=await connectWallet();setWallet(address);window.location.assign(checkoutUrl(plan?{...post,lock:plan.lock,network:plan.network}:post,address));}catch(e){setError(errorText(e));}}
  async function addComment(e:FormEvent){e.preventDefault();if(!post||!needUser())return;setCommentBusy(true);try{const r=await api<{comment:Comment}>("/api/comments",{postId:post.id,body:comment,parentId:replyTo?.id||null});setComments(c=>[...c,r.comment]);setComment("");setReplyTo(null);setPosts(ps=>ps.map(p=>p.id===post.id?{...p,comment_count:(p.comment_count||0)+1}:p));}catch(e){setError(errorText(e));}finally{setCommentBusy(false);}}
  async function deleteComment(id:string){try{await api(`/api/comments?comment=${id}`,undefined,"DELETE");setComments(c=>c.filter(x=>x.id!==id&&x.parent_id!==id));setToast("Comentario eliminado.");}catch(e){setError(errorText(e));}}
  async function report(targetType:"post"|"comment"|"creator",targetId:string){if(!needUser())return;const ok=window.confirm("¿Quieres enviar este contenido a moderación?");if(!ok)return;try{await api("/api/moderation",{action:"report",targetType,targetId,reason:"other",details:"Reportado desde la interfaz de KeyTube."});setToast("Reporte enviado para revisión.");}catch(e){setError(errorText(e));}}
  async function blockCreator(id:string){if(!needUser())return;const active=!account.blocked.includes(id);try{await api("/api/moderation",{action:"block",userId:id,active});setAccount(a=>({...a,blocked:active?[...a.blocked,id]:a.blocked.filter(x=>x!==id)}));setCreatorInfo(info=>info?{...info,blocked:active}:info);setToast(active?"Creador bloqueado.":"Creador desbloqueado.");if(active)navigate("/");}catch(e){setError(errorText(e));}}
  async function addToCollection(collectionId:string,p:PublicPost){try{await api("/api/collections",{action:"add",collectionId,postId:p.id});await loadCollections();setCollectionTarget(null);setToast("Añadido a la colección.");}catch(e){setError(errorText(e));}}
  async function createCollection(){if(!newCollection.trim())return;try{const r=await api<{collection:CollectionItem}>("/api/collections",{action:"create",name:newCollection.trim()});setNewCollection("");await loadCollections();if(collectionTarget)await addToCollection(r.collection.id,collectionTarget);}catch(e){setError(errorText(e));}}
  async function linkWallet(){if(!needUser())return;try{const address=await connectWallet({chooseAccount:true});const network=await walletNetwork();const proof=await signProof("wallet",address,network,{});await api("/api/wallet",{...proof,network});setWallet(address);await refreshAccount();setToast("Wallet vinculada.");}catch(e){setError(errorText(e));}}
  async function unlinkWallet(){try{await api("/api/wallet",undefined,"DELETE");setWallet(null);await refreshAccount();setToast("Wallet desvinculada.");}catch(e){setError(errorText(e));}}
  async function logout(){try{await api("/api/auth/logout",{});setUser(null);setAccount(emptyAccount);setFull(null);setWallet(null);setMyPlans([]);navigate("/");setToast("Sesión cerrada.");}catch(e){setError(errorText(e));}}

  const mine=posts.filter(p=>p.creator_id===user?.id);
  const creatorPosts=posts.filter(p=>p.creator_id===creatorId);
  const baseFeed=(feedMode==="forYou"&&user&&!studio&&!creatorId&&!savedView&&!followingView&&!historyView&&!collectionsView?recommended:posts);
  const contextPosts=studio?mine:creatorId?creatorPosts:savedView?posts.filter(p=>account.saved.includes(p.id)):followingView?posts.filter(p=>account.following.includes(p.creator_id||"")):baseFeed;
  const visible=contextPosts.filter(p=>
    (accessFilter==="all"||p.visibility===accessFilter)&&
    (filter==="Todos"||typeFilter[filter]===p.type||p.category===filter)&&
    (!creatorId||creatorTab==="all"||p.type===creatorTab)&&
    `${p.title} ${p.creator} ${p.category} ${p.intro}`.toLowerCase().includes(search.toLowerCase())
  );
  const filtered=[...visible].sort((a,b)=>sort==="oldest"?a.created_at-b.created_at:sort==="views_desc"?(b.views||0)-(a.views||0)||b.created_at-a.created_at:sort==="views_asc"?(a.views||0)-(b.views||0)||b.created_at-a.created_at:b.created_at-a.created_at);
  const trending=[...posts].sort((a,b)=>(b.views||0)-(a.views||0)+(b.likes||0)*3-(a.likes||0)*3).slice(0,5);
  const locked=!!post&&!full&&post.visibility!=="free";
  const eligible=creatorPlans.filter(p=>post&&(p.lock.toLowerCase()===post.lock.toLowerCase()||p.lock.toLowerCase()===post.premium_lock?.toLowerCase()));

  useEffect(()=>{filtered.slice(0,8).forEach(p=>router.prefetch(`/content/${p.id}`));},[filtered.map(p=>p.id).join("|"),router]);

  const renderPlans=(items:CreatorPlan[],buyButtons:boolean)=><div className="k2-plan-grid">{items.map(p=><article className={`k2-plan-card ${p.slot==="premium"?"premium":""}`} key={p.id}><span className="k2-badge"><KeyRound size={13}/>{p.slot==="basic"?"Básico":"Premium"}</span><h2>{p.name}</h2><p>{p.description}</p><div className="k2-price">{p.quote?`${p.quote.price} ${p.quote.currency}`:"Precio por confirmar"}<small>{p.quote?p.quote.duration:`${p.durationDays} días`}</small></div><ul>{p.slot==="premium"&&<li><Check size={16}/>Todo el contenido del Básico</li>}{p.benefits.map((b,i)=><li key={i}><Check size={16}/>{b}</li>)}<li><Check size={16}/>{p.coverage.map(t=>mediaLabels[t]).join(" · ")}</li></ul>{buyButtons&&<button className="k2-primary" onClick={()=>buy(p)}>Comprar {p.name}<ArrowRight size={16}/></button>}</article>)}</div>;

  const card=(p:PublicPost,index:number)=><div key={p.id} className="k2-feed-item"><ContentCard post={p} index={index+1} saved={account.saved.includes(p.id)} liked={account.liked.includes(p.id)||!!p.liked} following={account.following.includes(p.creator_id||"")} canFollow={!!p.creator_id&&p.creator_id!==user?.id} onOpen={()=>navigate(`/content/${p.id}`)} onSave={()=>social("save",p.id)} onLike={()=>social("like",p.id)} onFollow={()=>p.creator_id&&social("follow",p.creator_id)} onShare={()=>share(p)} onComments={()=>navigate(`/content/${p.id}#comments`)} onCreator={()=>navigate(`/creator/${p.creator_id||""}`)} onProgress={(s,pr)=>trackProgress(p.id,s,pr)}/>{studio&&<button className="k2-delete" onClick={()=>setDeletePost(p)}><Trash2 size={14}/> Eliminar publicación</button>}</div>;

  const historyPosts=history.map(h=>({h,p:posts.find(p=>p.id===h.post_id)})).filter((x):x is {h:HistoryItem;p:PublicPost}=>!!x.p);
  const collectionPostFor=(id:string)=>posts.find(p=>p.id===id);
  const coverUrl=creatorInfo?.profile.cover?.startsWith("asset:")?`/api/avatar/${creatorInfo.profile.cover.slice(6)}`:"";

  const navMain=[
    {url:"/",label:"Inicio",icon:Home},{url:"/explore",label:"Explorar",icon:Compass},{url:"/saved",label:"Guardados",icon:Bookmark},{url:"/following",label:"Siguiendo",icon:Users},
    {url:"/history",label:"Historial",icon:History},{url:"/collections",label:"Colecciones",icon:FolderHeart},{url:"/notifications",label:"Notificaciones",icon:Bell,badge:account.unreadNotifications},
  ];
  const navStudio=[{url:"/studio",label:"Mi contenido",icon:Play},{url:"/studio/upload",label:"Subir contenido",icon:Upload},{url:"/studio/stats",label:"Estadísticas",icon:BarChart3},{url:"/memberships",label:"Mis planes",icon:KeyRound},{url:"/profile",label:"Mi cuenta",icon:Settings}];

  return <div className="k2-app">
    <aside className={`k2-sidebar ${mobile?"open":""}`}><button className="k2-brand-link" onClick={()=>navigate("/")} aria-label="KeyTube inicio"><Brand/></button><nav aria-label="Principal">{navMain.map(n=><button key={n.url} className={path===n.url?"active":""} onClick={()=>{if(["/history","/collections","/notifications"].includes(n.url)&&!needUser())return;navigate(n.url);}}><n.icon size={19}/>{n.label}{!!n.badge&&<span className="k2-nav-badge">{n.badge>99?"99+":n.badge}</span>}</button>)}<span className="k2-nav-caption">TU ESTUDIO</span>{navStudio.map(n=><button key={n.url} className={path===n.url?"active":""} onClick={()=>{if(needUser())navigate(n.url);}}><n.icon size={19}/>{n.label}</button>)}{account.isAdmin&&<><span className="k2-nav-caption">ADMINISTRACIÓN</span><button className={adminView?"active":""} onClick={()=>navigate("/admin")}><Shield size={19}/>Moderación</button></>}</nav><div className="k2-sidebar-card"><Sparkles size={26}/><strong>Tu talento tiene valor.</strong><p>Comparte lo que creas. Construye tu comunidad.</p><button className="k2-primary" onClick={()=>{if(needUser())navigate("/studio/upload");}}>Empezar a crear</button></div><span className="k2-powered"><LockKeyhole size={15}/> Membresías con <strong>Unlock</strong></span></aside>

    <div className="k2-page"><header className="k2-topbar"><button className="k2-icon k2-mobile-menu" aria-label="Abrir menú" onClick={()=>setMobile(!mobile)}><Menu size={22}/></button><label className="k2-search"><Search size={19}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Busca creador, título, categoría o tema…" aria-label="Buscar contenido"/></label><div className="k2-top-actions">{user?<><button className="k2-icon k2-bell" onClick={()=>navigate("/notifications")} aria-label="Notificaciones"><Bell size={19}/>{account.unreadNotifications>0&&<span>{account.unreadNotifications>9?"9+":account.unreadNotifications}</span>}</button><button className="k2-secondary k2-upload-button" onClick={()=>navigate("/studio/upload")}><Plus size={17}/> Crear</button><button className="k2-user" onClick={()=>navigate("/profile")}><CreatorAvatar name={account.profile?.name||user.name} avatar={account.profile?.avatar}/><span>{account.profile?.name||user.name}</span>{!!account.profile?.verified&&<BadgeCheck size={15} className="kt-verified"/>}</button></>:<><button className="k2-secondary" onClick={()=>setAuth(true)}>Iniciar sesión</button><button className="k2-primary" onClick={()=>setAuth(true)}>Crear cuenta</button></>}</div></header>

    <main className="k2-main">{error&&<div className="k2-error k2-global-error" role="alert">{error}<button onClick={()=>setError("")} aria-label="Cerrar">×</button></div>}
    {(studio||statsView||planView||profileView||notificationsView||historyView||collectionsView||adminView)&&!user?<div className="k2-empty"><KeyRound size={40}/><h1>Entra a tu cuenta para continuar</h1><p>Crea tu perfil y disfruta todas las herramientas de KeyTube.</p><button className="k2-primary" onClick={()=>setAuth(true)}>Iniciar sesión o registrarme</button></div>:

    contentId?<>{post?<div className="k2-content-layout"><section><button className="k2-back" onClick={()=>navigate("/")}>← Volver a explorar</button><div className="k2-media-wrap"><ContentMedia post={post} full={full} initialPosition={resumePosition} onProgress={(s,pr)=>trackProgress(post.id,s,pr)} onPreviewEnd={()=>setPurchase(true)} onError={()=>{setFull(null);setError("No se pudo reproducir el archivo. Si tu acceso venció, vuelve a verificar tu membresía.");}}/>{locked&&purchase&&<div className="k2-player-gate"><span className="k2-large-lock"><LockKeyhole size={30}/></span><h2>Esto es solo el comienzo.</h2><p>Este contenido es exclusivo. Hazte miembro para disfrutarlo completo.</p><button className="k2-primary" onClick={()=>document.getElementById("buy-plans")?.scrollIntoView({behavior:"smooth"})}>Ver membresías<ArrowRight size={17}/></button></div>}</div>
      <div className="k2-post-heading"><span className={`k2-badge ${full?"free":""}`}>{full?<><Check size={12}/> Contenido completo</>:post.visibility==="free"?"Gratis":<><LockKeyhole size={12}/> Contenido exclusivo</>}</span><h1>{post.title}</h1><div className="k2-post-meta"><span><Eye size={14}/>{post.views||0} vistas</span><span><Heart size={14}/>{post.likes||0}</span><span><MessageCircle size={14}/>{post.comment_count||0}</span><span>{new Date(post.created_at).toLocaleDateString("es")}</span></div><div className="k2-row"><button className="k2-creator-button" onClick={()=>navigate(`/creator/${post.creator_id}`)}><CreatorAvatar name={post.creator} avatar={post.avatar}/><span><strong>{post.creator}{post.verified&&<BadgeCheck size={14} className="kt-verified"/>}</strong><small>{post.category} · {mediaLabels[post.type||"text"]}</small></span></button><button className={`k2-secondary ${account.liked.includes(post.id)||post.liked?"selected":""}`} onClick={()=>social("like",post.id)}><Heart size={17}/>{account.liked.includes(post.id)||post.liked?"Te gusta":"Me gusta"}</button><button className="k2-secondary" onClick={()=>social("follow",post.creator_id||"")}>{account.following.includes(post.creator_id||"")?"Siguiendo":"Seguir"}</button><button className="k2-icon" aria-label="Guardar" onClick={()=>social("save",post.id)}><Bookmark fill={account.saved.includes(post.id)?"currentColor":"none"} size={19}/></button><button className="k2-icon" aria-label="Compartir" onClick={()=>share(post)}><Share2 size={18}/></button><button className="k2-icon" aria-label="Colección" onClick={()=>{if(needUser())setCollectionTarget(post);}}><FolderHeart size={18}/></button><button className="k2-icon" aria-label="Reportar" onClick={()=>report("post",post.id)}><Flag size={17}/></button>{user?.id===post.creator_id&&<button className="k2-delete k2-delete-detail" onClick={()=>setDeletePost(post)}><Trash2 size={14}/> Eliminar</button>}</div><p>{post.intro}</p>{full?.body&&<div className="k2-full-text">{full.body}</div>}</div>
      {locked&&<section id="buy-plans" className="k2-access-panel"><span className="k2-eyebrow">TU LLAVE AL CONTENIDO COMPLETO</span><h2>Elige cómo apoyar a {post.creator}</h2><p>Cada membresía pertenece a este creador. El acceso se comprueba con tu Key de Unlock.</p>{renderPlans(eligible,true)}{!eligible.length&&<div className="k2-notice"><p>{legacyQuote?`${legacyQuote.name} · ${legacyQuote.price} ${legacyQuote.currency} · ${legacyQuote.duration}`:"El precio y la duración se muestran al abrir Unlock."}</p><button className="k2-primary" onClick={()=>buy()}>Comprar membresía<ExternalLink size={16}/></button></div>}<button className="k2-secondary k2-verify" disabled={verifying} onClick={verify}>{verifying?<LoaderCircle size={17} className="k2-spin"/>:<Wallet size={17}/>} {verifying?"Verificando membresía…":"Ya tengo membresía · verificar acceso"}</button><small>Después de comprar, verifica con la wallet que recibió la membresía.</small>{user?.id===post.creator_id&&<button className="k2-secondary" onClick={async()=>{try{setFull(await api<FullContent>(`/api/studio?post=${post.id}`));setPurchase(false);setToast("Vista privada del creador.");}catch(e){setError(errorText(e));}}}>Ver mi archivo completo</button>}</section>}
      <section className="k2-comments" id="comments"><h2><MessageCircle size={20}/> Comentarios <span>{comments.length}</span></h2>{replyTo&&<div className="k2-replying">Respondiendo a <strong>{replyTo.name}</strong><button onClick={()=>setReplyTo(null)}>×</button></div>}<form onSubmit={addComment}><input value={comment} onChange={e=>setComment(e.target.value)} minLength={2} maxLength={1000} required placeholder={user?replyTo?"Escribe tu respuesta…":"Comparte lo que te gustó…":"Inicia sesión para comentar"}/><button className="k2-primary" disabled={commentBusy}>Publicar</button></form><div className="k2-comment-tree">{comments.filter(c=>!c.parent_id).map(c=><div key={c.id} className="k2-comment-thread"><article><CreatorAvatar name={c.name} avatar={c.avatar}/><div><strong>{c.name}{!!c.verified&&<BadgeCheck size={13} className="kt-verified"/>}</strong><small>{new Date(c.created_at).toLocaleDateString("es")}</small><p>{c.body}</p><div className="k2-comment-actions"><button onClick={()=>setReplyTo(c)}>Responder</button><button onClick={()=>report("comment",c.id)}>Reportar</button>{(c.owner_id===user?.id||post.creator_id===user?.id)&&<button onClick={()=>deleteComment(c.id)}>Eliminar</button>}</div></div></article>{comments.filter(r=>r.parent_id===c.id).map(r=><article key={r.id} className="k2-comment-reply"><CreatorAvatar name={r.name} avatar={r.avatar}/><div><strong>{r.name}</strong><small>{new Date(r.created_at).toLocaleDateString("es")}</small><p>{r.body}</p><div className="k2-comment-actions">{(r.owner_id===user?.id||post.creator_id===user?.id)&&<button onClick={()=>deleteComment(r.id)}>Eliminar</button>}</div></div></article>)}</div>)}</div>{!comments.length&&<p>Sé la primera persona en comentar.</p>}</section></section><aside className="k2-related"><h3>Sigue descubriendo</h3>{posts.filter(p=>p.id!==post.id).slice(0,4).map(card)}</aside></div>:<div className="k2-empty"><LoaderCircle className="k2-spin"/><p>Cargando publicación…</p></div>}</>:

    upload?<><div className="k2-section-heading"><div><span className="k2-eyebrow">TU ESTUDIO CREATIVO</span><h1>Comparte algo extraordinario.</h1><p>Tu contenido, tus reglas. Decide qué muestras y qué desbloquean tus miembros.</p></div></div><Publisher creator={account.profile?.name||user!.name} plans={myPlans} onPublished={p=>{setToast("Tu publicación ya está disponible.");refreshPosts();refreshAccount();refreshRecommendations();navigate(`/content/${p.id}`);}}/></>:

    statsView?<><div className="k2-section-heading"><div><span className="k2-eyebrow">ANALÍTICA DEL CREADOR</span><h1>Estadísticas</h1><p>Entiende qué contenido conecta mejor con tu comunidad.</p></div><label className="k2-sort"><BarChart3 size={14}/><select aria-label="Periodo de estadísticas" value={statsPeriod} onChange={e=>setStatsPeriod(Number(e.target.value) as 7|30|90)}><option value={7}>7 días</option><option value={30}>30 días</option><option value={90}>90 días</option></select></label></div>{stats?<><div className="k2-metric-grid">{[["Publicaciones",stats.summary.posts],["Vistas",stats.summary.views],["Me gusta",stats.summary.likes],["Comentarios",stats.summary.comments],["Seguidores",stats.summary.followers],["Accesos verificados",stats.summary.accesses]].map(([label,value])=><article key={String(label)}><strong>{Number(value).toLocaleString("es-BO")}</strong><span>{label}</span></article>)}</div><section className="k2-chart-card"><div><h2>Actividad de los últimos {stats.period} días</h2><p>Me gusta, comentarios, nuevos seguidores y accesos verificados.</p></div><div className="k2-mini-chart" aria-label="Actividad diaria">{stats.series.map((d,i)=>{const max=Math.max(1,...stats.series.map(x=>x.total));return <span key={d.date} title={`${d.date}: ${d.total} interacciones`} style={{height:`${Math.max(4,(d.total/max)*100)}%`}}><i>{d.total}</i>{(i===0||i===stats.series.length-1||i%Math.max(1,Math.floor(stats.series.length/5))===0)&&<small>{d.date.slice(5)}</small>}</span>;})}</div></section><section className="k2-table-card"><h2>Contenido con mejor rendimiento</h2>{stats.top.map((p,i)=><button key={p.id} onClick={()=>navigate(`/content/${p.id}`)}><span>#{i+1}</span><strong>{p.title}</strong><small>{p.views} vistas · {p.likes} me gusta · {p.comments} comentarios</small><ArrowRight size={15}/></button>)}</section></>:<div className="k2-empty"><LoaderCircle className="k2-spin"/></div>}</>:

    planView?<><div className="k2-section-heading"><div><span className="k2-eyebrow">MONETIZA TU COMUNIDAD</span><h1>Dos planes. Tú decides el valor.</h1><p>Elige precio, duración, beneficios y formatos incluidos.</p></div><a className="k2-secondary" href="https://app.unlock-protocol.com/locks" target="_blank" rel="noreferrer">Panel de Unlock<ExternalLink size={16}/></a></div><div className="k2-wallet-panel"><div><Wallet size={20}/><span><strong>Wallet del creador</strong><small>{account.profile?.wallet?shortAddress(account.profile.wallet):"Todavía no vinculada"}</small></span></div><button className="k2-secondary" onClick={linkWallet}>{account.profile?.wallet?"Elegir otra wallet":"Elegir wallet en MetaMask"}</button></div><div className="k2-plan-grid">{(["basic","premium"] as const).map(slot=><PlanEditor key={`${slot}-${myPlans.find(p=>p.slot===slot)?.id||"new"}`} slot={slot} existing={myPlans.find(p=>p.slot===slot)} sibling={myPlans.find(p=>p.slot!==slot)} onSaved={()=>{refreshPlans();setToast("Plan conectado con Unlock.");}}/>)}</div></>:

    profileView?<><div className="k2-section-heading"><div><span className="k2-eyebrow">TU ESPACIO EN KEYTUBE</span><h1>Mi cuenta</h1><p>Perfil, seguridad, wallet y accesos.</p></div></div><div className="k2-profile-card"><div className="k2-profile-summary"><CreatorAvatar name={account.profile?.name||user!.name} avatar={account.profile?.avatar} size={72}/><div><h2>{account.profile?.name||user!.name}{!!account.profile?.verified&&<BadgeCheck size={18} className="kt-verified"/>}</h2><p>{user?.email}</p></div></div><div className="k2-stats"><span><strong>{account.postCount}</strong>Publicaciones</span><span><strong>{account.followerCount}</strong>Seguidores</span><span><strong>{account.following.length}</strong>Siguiendo</span><span><strong>{account.collectionCount}</strong>Colecciones</span><span><strong>{account.accessCount}</strong>Accesos</span></div><ProfileEditor profile={account.profile} fallbackName={user!.name} onSaved={async()=>{await refreshAccount();await refreshPosts();setToast("Perfil actualizado.");}}/><div className="k2-profile-links"><a className="k2-secondary" href="https://app.unlock-protocol.com/locks" target="_blank" rel="noreferrer"><KeyRound size={17}/> Panel de Unlock<ExternalLink size={15}/></a><button className="k2-secondary" onClick={linkWallet}><Wallet size={17}/>{account.profile?.wallet?`Wallet · ${shortAddress(account.profile.wallet)}`:wallet?`Elegir wallet · ${shortAddress(wallet)}`:"Elegir wallet"}</button>{account.profile?.wallet&&<button className="k2-secondary" onClick={unlinkWallet}><Unplug size={17}/> Desvincular wallet</button>}{google&&<a className="k2-secondary" href="/api/auth/google/start?link=1">Vincular Google</a>}<button className="k2-secondary" onClick={logout}><LogOut size={17}/> Cerrar sesión</button></div></div><section className="k2-access-history"><h2><CircleDollarSign size={20}/> Mis accesos verificados</h2>{accesses.length?accesses.slice(0,12).map(a=><button key={`${a.post_id}-${a.verified_at}`} onClick={()=>navigate(`/content/${a.post_id}`)}><strong>{a.title}</strong><span>{a.creator} · {new Date(a.verified_at).toLocaleDateString("es")}</span><ArrowRight size={15}/></button>):<p>Aquí aparecerán los contenidos de membresía que verifiques con tu wallet.</p>}</section></>:

    notificationsView?<><div className="k2-section-heading"><div><span className="k2-eyebrow">TU COMUNIDAD</span><h1>Notificaciones</h1><p>Seguidores, me gusta, comentarios, respuestas y accesos de miembros.</p></div><button className="k2-secondary" onClick={async()=>{await api("/api/notifications",{all:true});setNotifications(n=>n.map(x=>({...x,read_at:Date.now()})));setAccount(a=>({...a,unreadNotifications:0}));}}><CheckCheck size={16}/> Marcar todo leído</button></div><div className="k2-notification-list">{notifications.map(n=><button key={n.id} className={!n.read_at?"unread":""} onClick={async()=>{await api("/api/notifications",{id:n.id});if(!n.read_at){setNotifications(items=>items.map(x=>x.id===n.id?{...x,read_at:Date.now()}:x));setAccount(a=>({...a,unreadNotifications:Math.max(0,a.unreadNotifications-1)}));}if(n.target_id&&n.type==="follow")navigate(`/creator/${n.target_id}`);else if(n.target_id&&(n.type==="like"||n.type==="comment"||n.type==="reply"||n.type==="member"||n.type==="new_post"))navigate(`/content/${n.target_id}`);}}><span className="k2-notification-icon">{n.type==="like"?<Heart size={18}/>:n.type==="follow"?<Users size={18}/>:n.type==="member"?<KeyRound size={18}/>:<MessageCircle size={18}/>}</span><span><strong>{n.message}</strong><small>{new Date(n.created_at).toLocaleString("es-BO")}</small></span>{!n.read_at&&<i/>}</button>)}{!notifications.length&&<div className="k2-empty"><Bell size={36}/><h2>Todo tranquilo por aquí</h2><p>Cuando alguien interactúe contigo aparecerá aquí.</p></div>}</div></>:

    historyView?<><div className="k2-section-heading"><div><span className="k2-eyebrow">CONTINÚA DONDE QUEDASTE</span><h1>Historial</h1><p>Videos, canciones y publicaciones que has abierto recientemente.</p></div></div>{historyPosts.length?<div className="k2-grid">{historyPosts.map(({p,h},i)=><div key={p.id}><div className="k2-progress-label"><span>{h.progress>=95?"Completado":`Progreso ${h.progress}%`}</span><div><i style={{width:`${h.progress}%`}}/></div></div>{card(p,i)}</div>)}</div>:<div className="k2-empty"><History size={38}/><h2>Aún no tienes historial</h2><p>Abre contenido y podrás retomarlo desde aquí.</p></div>}</>:

    collectionsView?<><div className="k2-section-heading"><div><span className="k2-eyebrow">ORGANIZA LO QUE TE INSPIRA</span><h1>Colecciones</h1><p>Crea listas para música, cursos, documentos, favoritos y más.</p></div><div className="k2-inline-create"><input value={newCollection} onChange={e=>setNewCollection(e.target.value)} placeholder="Nueva colección"/><button className="k2-primary" onClick={createCollection}><Plus size={16}/> Crear</button></div></div>{collections.length?<div className="k2-collections-grid">{collections.map(c=><section key={c.id}><h2>{c.name}</h2><small>{c.item_count} elementos</small>{collectionPosts.filter(x=>x.collection_id===c.id).map(item=>{const p=collectionPostFor(item.post_id);return <button key={item.post_id} onClick={()=>navigate(`/content/${item.post_id}`)}><strong>{p?.title||item.title}</strong><span>{p?.creator||item.creator}</span><ArrowRight size={14}/></button>})}</section>)}</div>:<div className="k2-empty"><FolderHeart size={38}/><h2>Crea tu primera colección</h2><p>Agrupa contenido según tus intereses.</p></div>}</>:

    adminView?<><div className="k2-section-heading"><div><span className="k2-eyebrow">SEGURIDAD DE LA COMUNIDAD</span><h1>Moderación</h1><p>Revisa reportes y gestiona el estado de los casos.</p></div></div>{account.isAdmin?<div className="k2-report-list">{reports.map(r=><article key={r.id}><span className={`k2-report-status ${r.status}`}>{r.status}</span><h3>{r.target_type} · {r.reason}</h3><p>{r.details||"Sin detalles adicionales."}</p><small>Reportado por {r.reporter_name} · {new Date(r.created_at).toLocaleString("es-BO")}</small><div className="k2-row"><button className="k2-secondary" onClick={async()=>{await api("/api/moderation",{id:r.id,status:"resolved"},"PATCH");setReports(x=>x.map(i=>i.id===r.id?{...i,status:"resolved"}:i));}}>Resolver</button>{r.target_type==="creator"&&<button className="k2-secondary" onClick={async()=>{await api("/api/moderation",{id:r.id,status:"resolved",verifyCreator:r.target_id,verified:true},"PATCH");setToast("Creador verificado.");}}>Verificar creador</button>}</div></article>)}{!reports.length&&<div className="k2-empty"><Shield size={38}/><h2>No hay reportes pendientes</h2></div>}</div>:<div className="k2-empty"><Shield size={38}/><h2>Acceso restringido</h2></div>}</>:

    <><div className="k2-feed-layout"><section className="k2-feed">{!studio&&!savedView&&!followingView&&!creatorId&&path==="/"&&<div className="k2-hero"><div><span className="k2-eyebrow">EL CONTENIDO QUE TE CONECTA</span><h1>Lo que te apasiona,<br/>ahora tiene <em>llave.</em></h1><p>Descubre, disfruta y apoya a tus creadores.</p><button className="k2-primary" onClick={()=>document.getElementById("feed-content")?.scrollIntoView({behavior:"smooth"})}>Explorar contenido<ArrowRight size={17}/></button><span className="k2-hero-unlock"><LockKeyhole size={16}/> Powered by <strong>Unlock</strong></span></div></div>}
    {creatorId&&creatorInfo&&<div className="k2-creator-hero k2-creator-pro" style={coverUrl?{backgroundImage:`linear-gradient(90deg,#07101aec,#07101ab5),url(${coverUrl})`}:undefined}><CreatorAvatar name={creatorInfo.profile.name} avatar={creatorInfo.profile.avatar} size={82}/><span className="k2-eyebrow">ESPACIO DEL CREADOR</span><h1>{creatorInfo.profile.name}{!!creatorInfo.profile.verified&&<BadgeCheck size={24} className="kt-verified"/>}</h1><p>{creatorInfo.profile.bio||"Creador en KeyTube."}</p><div className="k2-creator-numbers"><span><strong>{creatorInfo.profile.post_count}</strong>publicaciones</span><span><strong>{creatorInfo.profile.follower_count}</strong>seguidores</span><span><strong>{creatorInfo.profile.total_views}</strong>vistas</span><span><strong>{creatorInfo.profile.total_likes}</strong>me gusta</span></div><div className="k2-creator-socials">{creatorInfo.profile.website&&<a href={creatorInfo.profile.website} target="_blank" rel="noreferrer"><LinkIcon size={15}/>Web</a>}{creatorInfo.profile.instagram&&<a href={creatorInfo.profile.instagram} target="_blank" rel="noreferrer">Instagram</a>}{creatorInfo.profile.youtube&&<a href={creatorInfo.profile.youtube} target="_blank" rel="noreferrer">YouTube</a>}</div><div className="k2-row"><button className="k2-primary" onClick={()=>social("follow",creatorId)}>{account.following.includes(creatorId)?<><UserRoundCheck size={16}/> Siguiendo</>:<><Users size={16}/> Seguir creador</>}</button><button className="k2-secondary" onClick={()=>report("creator",creatorId)}><Flag size={15}/> Reportar</button><button className="k2-secondary" onClick={()=>blockCreator(creatorId)}><Ban size={15}/>{account.blocked.includes(creatorId)?"Desbloquear":"Bloquear"}</button></div><div className="k2-creator-tabs">{[["all","Todo"],["video","Videos"],["image","Imágenes"],["audio","Música"],["document","Documentos"]].map(([v,l])=><button key={v} className={creatorTab===v?"active":""} onClick={()=>setCreatorTab(v)}>{l}</button>)}</div></div>}
    <div className="k2-section-heading" id="feed-content"><div><span className="k2-eyebrow">{studio?"TU ESTUDIO":feedMode==="forYou"&&user&&!creatorId?"RECOMENDADO PARA TI":"HECHO POR PERSONAS, PARA PERSONAS"}</span><h2>{studio?"Mi contenido":savedView?"Tus favoritos, siempre cerca":followingView?"De los creadores que sigues":creatorId?"Publicaciones del creador":feedMode==="forYou"&&user?"Para ti":"Descubre algo que te inspire"}</h2></div>{studio?<button className="k2-primary" onClick={()=>navigate("/studio/upload")}><Plus size={17}/> Publicar</button>:!creatorId&&<div className="k2-feed-mode"><button className={feedMode==="forYou"?"active":""} disabled={!user} onClick={()=>{if(needUser())setFeedMode("forYou");}}><Sparkles size={15}/>Para ti</button><button className={feedMode==="discover"?"active":""} onClick={()=>setFeedMode("discover")}><Compass size={15}/>Descubrir</button></div>}</div>
    <div className="k2-filter-row">{filters.map(f=><button key={f.name} className={filter===f.name?"active":""} onClick={()=>setFilter(f.name)}><f.icon size={16}/>{f.name}</button>)}<select aria-label="Categoría" value={CATEGORIES.slice(5).includes(filter)?filter:""} onChange={e=>setFilter(e.target.value||"Todos")}><option value="">Más categorías</option>{CATEGORIES.slice(5).map(c=><option key={c}>{c}</option>)}</select><label className="k2-sort"><ListFilter size={14}/><select aria-label="Acceso" value={accessFilter} onChange={e=>setAccessFilter(e.target.value as typeof accessFilter)}><option value="all">Gratis y de pago</option><option value="free">Solo gratis</option><option value="members">Solo miembros</option></select></label><label className="k2-sort"><ArrowDownUp size={14}/><select aria-label="Ordenar" value={sort} onChange={e=>setSort(e.target.value as SortMode)}><option value="newest">Más recientes</option><option value="oldest">Más antiguas</option><option value="views_desc">Más vistas</option><option value="views_asc">Menos vistas</option></select></label></div>
    {loading?<div className="k2-empty"><LoaderCircle className="k2-spin"/><p>Cargando contenido…</p></div>:filtered.length?<div className="k2-grid">{filtered.map(card)}</div>:<div className="k2-empty"><Compass size={36}/><h2>{studio?"Tu primera publicación empieza aquí":"No encontramos contenido"}</h2><p>{search?"Prueba otra búsqueda o quita algún filtro.":"Explora nuevas categorías o creadores."}</p><button className="k2-secondary" onClick={()=>{setFilter("Todos");setAccessFilter("all");setSearch("");navigate("/");}}>Limpiar filtros</button></div>}
    {creatorId&&!!creatorPlans.length&&<section className="k2-creator-plans"><h2>Membresías de {creatorInfo?.profile.name}</h2>{renderPlans(creatorPlans,false)}<p>Abre una publicación para elegir el plan que la desbloquea.</p></section>}</section>
    {!studio&&<aside className="k2-discover-aside"><div className="k2-community-card"><span className="k2-large-lock"><KeyRound size={28}/></span><h2>Más contenido.<br/>Más cerca.</h2><p>Una membresía, una conexión directa con quienes te inspiran.</p><button className="k2-secondary" onClick={()=>{if(needUser())navigate("/memberships");}}>Crear mis planes<ArrowRight size={15}/></button></div><div className="k2-trending-list"><h3><TrendingUp size={18}/> Tendencias</h3>{trending.length?trending.map((p,i)=><button key={p.id} onClick={()=>navigate(`/content/${p.id}`)}><span className="k2-trend-rank">{String(i+1).padStart(2,"0")}</span><span><strong>{p.title}</strong><small>{p.creator} · {p.views||0} vistas · {p.likes||0} ♥</small></span><ArrowRight size={15}/></button>):<p className="k2-trend-empty">Las tendencias aparecerán cuando haya publicaciones.</p>}</div><div className="k2-creators-list"><h3>Conoce a los creadores</h3>{Array.from(new Map(posts.map(p=>[p.creator_id,p])).values()).slice(0,5).map(p=><button key={p.creator_id} onClick={()=>navigate(`/creator/${p.creator_id}`)}><CreatorAvatar name={p.creator} avatar={p.avatar}/><span><strong>{p.creator}{p.verified&&<BadgeCheck size={12} className="kt-verified"/>}</strong><small>{p.category}</small></span><ArrowRight size={16}/></button>)}</div><div className="k2-tip"><Upload size={23}/><h3>También puedes crear.</h3><p>Publica gratis o comparte contenido exclusivo.</p><button onClick={()=>{if(needUser())navigate("/studio/upload");}}>Abrir mi estudio →</button></div></aside>}</div></>}
    </main><footer className="k2-footer"><Brand/><span>Tu contenido. Tu comunidad. Tu llave.</span><a href="https://unlock-protocol.com" target="_blank" rel="noreferrer">Conoce Unlock ↗</a></footer></div>

    {auth&&<Modal title="Acceso a KeyTube" onClose={()=>setAuth(false)}>{error&&<p className="k2-error" role="alert">{error}</p>}<AuthForm googleEnabled={google} recoveryEnabled={recovery} onSuccess={()=>{setAuth(false);refreshAccount().then(()=>refreshRecommendations());setToast("Ya estás en KeyTube.");}}/></Modal>}
    {deletePost&&<Modal title="Eliminar publicación" onClose={()=>{if(!deleting)setDeletePost(null);}}><h2>¿Eliminar esta publicación?</h2><p>«{deletePost.title}» dejará de estar disponible.</p><div className="k2-row"><button className="k2-secondary" disabled={deleting} onClick={()=>setDeletePost(null)}>Cancelar</button><button className="k2-primary" disabled={deleting} onClick={async()=>{setDeleting(true);try{const id=deletePost.id;await api(`/api/studio?post=${id}`,undefined,"DELETE");setDeletePost(null);await refreshPosts();await refreshAccount();if(contentId===id)navigate("/studio");setToast("Publicación eliminada.");}catch(e){setError(errorText(e));}finally{setDeleting(false);}}}>Eliminar</button></div></Modal>}
    {collectionTarget&&<Modal title="Añadir a colección" onClose={()=>setCollectionTarget(null)}><h2>Guardar «{collectionTarget.title}»</h2><div className="k2-collection-picker">{collections.map(c=><button className="k2-secondary" key={c.id} onClick={()=>addToCollection(c.id,collectionTarget)}><FolderHeart size={16}/>{c.name}<span>{c.item_count}</span></button>)}</div><div className="k2-inline-create"><input value={newCollection} onChange={e=>setNewCollection(e.target.value)} placeholder="Nueva colección"/><button className="k2-primary" onClick={createCollection}><Plus size={16}/>Crear y añadir</button></div></Modal>}
    {toast&&<div className="k2-toast" role="status"><Check size={18}/>{toast}</div>}
  </div>;
}
